### ISSUE TITLE
JSON-LD, JSON, or something else for versions document?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#1]
What syntax should the inventory/versions document have?

Discussion from draft document:

> @zimeon: JSON-LD is great, but is in the middle of upheaval from v1.0 to v1.1. and v1.2 could easily come along in a couple more years. I have some concerns that it is too much of a moving target for an internal repository data format in systems that will have archival application

> @julianmorley: +1

> @ahankinson: Yes, but ... :) I would probably prefer JSON-LD in its unstable forms, over arbitrary non-typed JSON.

**Comment by zimeon** [comment]
It seems to me unlikely that we'll propose JSON-LD that must be processed as such (with a JSON-LD aware parser). I expect all clients will process simply as JSON and we must thus specify a specific JSON form. This is like the situation with IIIF.

The difference between this and IIIF in my mind is that I can't think of a situation where one might want to interpret the data as RDF... which then begs the question of what JSON-LD buys us? Is it just that it is more self-documenting?

**Comment by ahankinson** [comment]
Self-documenting is quite a nice feature to have. There's also the question of lossless serialization _from_ RDF, since we know of at least one LDP implementation interested in OCFL.

It's ultimately a question of how many bets can we hedge... JSON-LD can be interpreted as just JSON, or it can be interpreted into more semantically useful contexts, should the need arise.

**Comment by zimeon** [comment]
To re-iterate: JSON-LD can be interpreted as JSON only if one defines a fixed JSON format (i.e. a specific MUST USE context and framing) as we do with IIIF

**Comment by zimeon** [comment]
Proposal:
  * OCFL inventory files will be valid JSON-LD, and named with a `.jsonld` extension 
  * We develop OCFL against the evolving JSON-LD 1.1 effort (as [IIIF has done with v3.0](http://iiif.io/api/image/3.0/change-log/#141-use-json-ld-11))
  * The inventory files MUST reference a specific `@context` that will be on ocfl.io. This will be make the files more self-documenting and able to be read as RDF. Development of the context file is in-scope for the specification effort
  * The structure of the inventory files will be defined in terms of a fixed JSON format. Clients will not need to include a full JSON-LD parser but can instead rely on the plain JSON structure
  * Through the development of an appropriate [JSON-LD frame](https://json-ld.org/spec/latest/json-ld-framing/) it will be possible to serialize an inventory in RDF in the correct JSON/JSON-LD form BUT _development of this frame is out-of-scope of the specification effort_
  * Following best practices in JSON-LD 1.1 we will alias `@id` to `id` and `@type` to `type` in the context (see [rationale for IIIF](http://iiif.io/api/image/3.0/change-log/#121-rename-id-to-id-type-to-type))

**Comment by zimeon** [comment]
Agreed and created follow-up issues #41 and #53
