### ISSUE TITLE
Set up CI to validate gitbook source?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#11]
I'm not sure how to do this but it would be useful to have CI running on PRs so that we know they don't break the spec. We use [travis on the IIIF specs for example](https://github.com/IIIF/api/blob/master/.travis.yml), I'm sure it would also be possible with circle-ci though I'm not familiar with that.

**Comment by ahankinson** [comment]
I'll set this up; I'll see if I can set it to push to gh-pages automatically on accepting a PR too.

**Comment by awoods** [comment]
Related to: https://github.com/OCFL/spec/issues/12

**Comment by rosy1280** [comment]
fyi travis is changing the way they integrate with github (in case you didn't see)

**Comment by zimeon** [comment]
We no longer use gitbook but moved to respec per #13, closing `wont-fix`
