### ISSUE TITLE
Terms for Implementation Notes

### ISSUE THREAD

**Issue by rosy1280** [OCFL/spec#112]
Terms to be defined in implementation notes:
- Additions
- Deletions
- Purge
- Rename

**Comment by rosy1280** [comment]
@OCFL/editors there was conversation about whether or not we should have terms in the implementation notes.  does anyone (@zimeon) remember where that landed?

**Comment by zimeon** [comment]
I would prefer not to have a new set of terms for the implementation document as it is a non-normative document. It should freely link to terms and sections in the spec but explain any new language in the flowing text.

**Comment by rosy1280** [comment]
closing this because we won't be adding these terms to the implementation notes
