### ISSUE TITLE
Auto-deploy gh-pages on commit

### ISSUE THREAD

**Issue by awoods** [OCFL/spec#12]
Currently, the [hosted book](https://ocfl.github.io/spec/) ( `gh-pages` ) and `master` become out of date unless the [build.sh](https://github.com/OCFL/spec/blob/master/build.sh) script is run. 
This issue is to instead auto-deploy to the `gh-pages` branch on every commit to `master`.
see: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by ahankinson** [comment]
NB: This will require an external build system (like Travis).

**Comment by awoods** [comment]
The most recent commit is now available at https://ocfl.io
