### ISSUE TITLE
Updates to Implementation Notes

### ISSUE THREAD

**Issue by rosy1280** [OCFL/spec#129]
- [x] ~~Section 1: Put OAIS in references. Link to it.~~
- [x] Section 4: include conformance declaration as reserved file
- [x] Section 5: Change heading to Storage
- [x] Section 5: Change "the paths of physical stored files" to "stored file paths"
- [x] Section 5 Change "version by reference to the manifest entry, not the actual path on disk." to  "version by referencing the manifest entry, not the actual path on disk."
- [x] Overall: Typos and spelling
- [x] Overall: Add basic file operation section before section 7
- [x] Section 9: link to the fixity block section of the spec
- [x] ~~Overall: Consider linking to definitions~~
- [x] Overall: Add a section about Storage Root Hierarchy

**Comment by zimeon** [comment]
https://github.com/OCFL/spec/pull/161 does #1 above and some typos

**Comment by zimeon** [comment]
@neilsjefferies  IMO yes, we can and should link to sections of the spec from the implementation notes
