### ISSUE TITLE
Change OCFL Collection to OCFL Storage Root in spec

### ISSUE THREAD

**Issue by ahankinson** [OCFL/spec#14]

**Comment by zimeon** [comment]
It seems that the word "collection" has enough baggage to fill a supertanker and should be avoided in nearly every library context... which is a long-winded way of saying ":+1: let's say OCFL Storage Root"

The word collection does not appear in the current skeletal draft so perhaps this is no-op re spec for now, just remember as we write more?

**Comment by zimeon** [comment]
Seems that #19 has already adopted this terminology. Propose `close`

**Comment by awoods** [comment]
Resolved with: https://github.com/OCFL/spec/pull/27
