### ISSUE TITLE
Digests should be hex encoded not base64

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#146]
I think whoever (cough) wrote the current draft of the [Digests section](https://ocfl.io/draft/spec/#digests) had too much [RFC3230 HTTP Digest header in base64](https://tools.ietf.org/html/rfc3230#section-4.1.1) on his mind from other work. I don't think we want base64, I think we want hex encoding like the output of `md5sum` and `shasum`. I also think it would be helpful to add an example (digest of empty string/file) in the table to make it very clear.

**Comment by julianmorley** [comment]
Concur that we want to specify hex encoding for the checksums.

**Comment by pwinckles** [comment]
Understanding that this is a long dead ticket, I was wondering about the reasoning for the hex preference. Because it's a more common, case insensitive representation?

I was thinking about it this morning, and, if base64 were allowed, there would be about a ~30% savings in digest representations.
