### ISSUE TITLE
Should we insist on lowercase hex letters in digests?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#149]
RFC4648 and Bagit allow either case for digests, so:

```
d41d8cd98f00b204e9800998ecf8427e
D41d8CD98F00B204E9800998ECF8427E
d41d8Cd98f00B204e9800998ECf8427e
```

are all valid as the MD5 of "".

We could follow this, we could SHOULD lowercase, or we could MUST lowercase. We should specify whichever. (Follow on from #146.)

**Comment by zimeon** [comment]
I lean toward **"MUST use lowercase"**. I don't see the advantage in allowing variability and the common tools use lowercase.

**Comment by awoods** [comment]
Coming from a position of not know what case ALL of the tools produce, and taking the lead from https://tools.ietf.org/html/rfc4648, I would be inclined to **"SHOULD use lowercase"**... recognizing that supporting upper or mixed case adds complexity to validation tooling.

**Comment by ahankinson** [comment]
I have made a new issue for the implementation guidelines to clarify that if you are relying on string comparison for checksum identification, that you should first cast the string to one case or another. Would that be an appropriate solution?

**Comment by zimeon** [comment]
So, if it is not MUST, are we OK with the following?

```
  "manifest": { "abc": [ "v1/foo.xml" ] }
  "v1" {
    "state": { "ABC": [ "v1/foo.xml" ] }
  }
```

**Comment by ahankinson** [comment]
I think we have to be, as messy as that is.

**Comment by awoods** [comment]
Or we could have SHOULD be lowercase and MUST be consistent across `manifest` and `state`.

**Comment by ahankinson** [comment]
We could make it a warning in the validator ("Mixed case digests in inventory")

**Comment by zimeon** [comment]
Regarding https://github.com/OCFL/spec/issues/149#issuecomment-420662344, there are currently no tools that produce or consume OCFL inventories so I don't think we are constrained by what existing tools do. If someone uses a digest tool/library that writes/generates hex using uppercase that could trivially be converted to lowercase within the OCFL inventory tooling

**Comment by ahankinson** [comment]
I think the concern was that if the Python checksum library produced uppercase digests, and the Java one produced lowercase digests, both should be usable without needing special (normative) OCFL tooling to normalize that.

**Comment by zimeon** [comment]
I don't see that as a concern, to me the tooling for dealing with OCFL inventory documents would just lowercase, e.g. Python: `digest.lower()`, Java: `digest.toLowerCase()`, etc...

**Comment by ahankinson** [comment]
Sure; but that would have to take place at the implementation level, so I don't think we can make a requirement for it at the specification level.

**Comment by ahankinson** [comment]
If we're specifying that the digests must conform to base16 as defined in RFC4648, then we should note that it says:

```
Essentially, Base 16 encoding is the standard case-insensitive hex encoding and may be referred to as "base16" or "hex".
```

Putting constraints by specifying case would mean we are arguably not following the RFC.

**Comment by awoods** [comment]
Assuming we do not want to specify counter to RFC4648, a non-normative note to raise awareness of the potential for case-conflicts seems like a very reasonable and helpful solution.

**Comment by zimeon** [comment]
Seems that opinion so far is that we should be case insensitive. I don't see any point in a "SHOULD lowercase" because code will still have to deal with both cases, and even saying "references MUST be consistent" seems a confusing partial restriction. Thus I'm for all or nothing and it seems nothing is getting the nod. I propose **close/agreed case insensitive with #155 as the resolution in spec**

**Comment by awoods** [comment]
Resolved by: https://github.com/OCFL/spec/pull/155
