### ISSUE TITLE
'should' should be uppercased in Version Immutability

### ISSUE THREAD

**Issue by ahankinson** [OCFL/spec#162]
In the section on Version Immutability, the sentence:

`Previous versions of an object should be considered immutable`

Should be:

`Previous versions of an object SHOULD be considered immutable`

per our conversation at the F2F meeting that Versions are not required to be immutable.

**Comment by rosy1280** [comment]
This is in the implementation notes.  I thought we weren't using spec language there.

**Comment by zimeon** [comment]
I agree with @rosy1280, the implementation notes are non-normative and hence no RFC2119 words

**Comment by ahankinson** [comment]
Sorry -- my bad.
