### ISSUE TITLE
make sure we're consistently using logical state

### ISSUE THREAD

**Issue by rosy1280** [OCFL/spec#163]
sometimes state appears by itself; other times its referred as state block; still others call it logical state.

**Comment by zimeon** [comment]
I think we can usefully distinguish:
  1. "logical state" - to talk about the set of bitstreams and their layout in a version, as defined in https://ocfl.io/draft/spec/#dfn-logical-state
  2. "`state` block" - the part of a [version description in the inventory](https://ocfl.io/draft/spec/#version) that describes the logical state, always using `code font` for `state` in this case
