### ISSUE TITLE
Check use of fixity checks

### ISSUE THREAD

**Issue by rosy1280** [OCFL/spec#165]
how do we refer to fixity checks in the document.  is it the act of checking fixity.  is it the digest used for checking fixity.  we should be consistent.

**Comment by neilsjefferies** [comment]
From the notes..."The digests in the inventory are used by OCFL for content addressability rather than fixity but they are suitable for use as part of a fixity regime, and the <code>manifest</code> block usefully identifies all the files in an OCFL Object..."
