### ISSUE TITLE
Stub records

### ISSUE THREAD

**Issue by tomwrobel** [OCFL/spec#170]
The implementation notes, para 10 File purging:

"The new object will be unlikely to have the same identifer as the orignal object so the deleted object can be replaced by a stub object that directs users and software to the new version."

Main question: Is it intended that a 'stub record' will be an OCFL-defined and specified format, or will this be implementation specific?

In addition, for our use cases, I think we would NOT want to change identifier. I would think we would want the OCFL identifier to be predictably derived from a record id. Otherwise we'd have to maintain a separate ORA/OCFL mapping table (or equivalent) somewhere. (eg uuid:12345678-1234-1234-12345678abcd would have OCFL identifier ora:ocfl/uuid:12345678-1234-1234-12345678abcd).

**Comment by zimeon** [comment]
IMO, a stub or tombstone record would be implementation specific. However, we should make that clear 

(and thanks for you comments @tomwrobel, keep 'em coming!)

**Comment by tomwrobel** [comment]
@awoods 

We've always approached this discussion through the lens of Fedora 3 (which is our existing solution). Versions are not immutable in F3, and so out underlying assumptions are that a) we don't need or expect version immutability and b) we will need the ability to purge individual files (Fedora 3 purge datastream-style behaviour).

However, after some thought: we don't need version immutability, but it doesn't hurt us so long as we can purge and recreate objects at need. 

We also don't mint a lot of our URIs, but inherit them from upstream services, so creating a new object isn't as simple as it may seem on paper. It may be my naivety, but I can't imagine an ORA implementation where the OCFL object URI is not in some way derived from the ORA object URI - therefore it's unlikely that we would want to change the OCFL URI if the original (cleaned) object still existed. 

However, while I can think of a number of cases where we would absolutely want to purge a file (e.g. illegal content, regulatory requirements, dangerous content such as a trojan), such occurances are extremely rare in practice (one or two times over the last two years). So a manual edit is fine.

**Comment by rosy1280** [comment]
there are updates in PR #179 that may address the question about stub records.  also pulling in @neilsjefferies since the thoughts in the PR are his not mine.

**Comment by neilsjefferies** [comment]
Reworded the purge section of implementation notes. There's no reason why a recreated object can't have the same identifier as the old one - a stub is only needed if it doesn't. Stubs are implementation dependent. However, the foibles of F3 should not be a primary design consideration.
