### ISSUE TITLE
Do we need hex stickers??

### ISSUE THREAD

**Issue by neilsjefferies** [OCFL/spec#201]

**Comment by ahankinson** [comment]
1. Yes
2. Will this require a less tongue-in-cheek logo?

**Comment by rosy1280** [comment]
YES PLEASE!

And I do think we need to rethink the logo.

**Comment by awoods** [comment]
I kind of like the lightening bolt :)

**Comment by zimeon** [comment]
I also like our retro logo

**Comment by rosy1280** [comment]
I was just thinking making something a bit more polished.  I might know someone could help.

**Comment by neilsjefferies** [comment]
...there is a certain Taco Bell-ness to the current logo...

**Comment by awoods** [comment]
![Old Logo?](https://avatars0.githubusercontent.com/u/35607965?s=200&v=4) ![taco_bell_logo svg](https://user-images.githubusercontent.com/149283/46640310-33f3f300-cb39-11e8-8b9e-a9cf26a5a065.png)

**Comment by neilsjefferies** [comment]
More Taco Bell's reputation for giving you painful nether regions....

**Comment by awoods** [comment]
Bursting 1<a href="https://dura-videos.s3.amazonaws.com/20190614_hand_2014.png"><img src="https://dura-videos.s3.amazonaws.com/20190614_hand_2014.png" width="196" title="bursting 1"></img></a>
