### ISSUE TITLE
Rules for JSON formatting

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#206]
I see one major inconsistency in our JSON formatting: are there spaces inside `[` and `]`. ie.

```
"state": {
    "4d27c8...b53": [ "foo/bar.xml" ],
    "cf83e1...a3e": [ "empty.txt", "empty2.txt" ]
  }
```

or

```
"state": {
    "4d27c8...b53": ["foo/bar.xml"],
    "cf83e1...a3e": ["empty.txt", "empty2.txt"]
  }
```

I note that the Moab examples have two spaces after the `:` in the state blocks, which should also be changed to one.

**Comment by ahankinson** [comment]
I would vote for the second option for formatting, if we were voting.

**Comment by awoods** [comment]
No preference here... beyond a vote for consistency.

**Comment by neilsjefferies** [comment]
Likewise no prefernce...second it is then.

**Comment by zimeon** [comment]
I have preference for the first form (which I why I used it)... so down to @rosy1280 to tie break

**Comment by ahankinson** [comment]
Oops, sorry @neilsjefferies

**Comment by rosy1280** [comment]
i vote for option 1

**Comment by julianmorley** [comment]
option 1

**Comment by ahankinson** [comment]
Assigning to myself for PR
