### ISSUE TITLE
Clarify that an empty object MUST have at least a v1 folder

### ISSUE THREAD

**Issue by ahankinson** [OCFL/spec#216]
... or not?

**Comment by zimeon** [comment]
I feel it is already quite clear, in https://ocfl.io/draft/spec/#version-directories :

> OCFL Object content is stored as a sequence of one or more versions.

and in https://ocfl.io/draft/spec/#versions :

> The versions array MUST be a list of one or more JSON objects, one for each 3.5.3.1 Version.

**Comment by awoods** [comment]
Section 3.3 seems like the place where we would clarify this, if any clarification is needed.
Although I agree that the snippets highlighted by @zimeon clearly imply the requirement of at least one version directory, I also feel that a `MUST` statement would be helpful.

Maybe something as simple as changing:
> OCFL Object content is stored as a sequence of one or more versions.

to:
> OCFL Object content MUST be stored as a sequence of one or more versions.

**Comment by rosy1280** [comment]
i agree with @zimeon that it is clear, but i also think that further clarifying isn't a problem so +1 on @awoods 's suggestion
