### ISSUE TITLE
Add inventory schema to Storage Root?

### ISSUE THREAD

**Issue by awoods** [OCFL/spec#223]
From a preservation/validation perspective, would it be appropriate to require the existence of a plain-text inventory schema at the Storage Root?

**Comment by ahankinson** [comment]
As mentioned by @zimeon, if we are allowing mixed versions of OCFL objects in a storage root, we will have to allow multiple schema files to validate them.

**Comment by awoods** [comment]
Agreed, this suggestion would require support for multiple schema documents.

**Comment by neilsjefferies** [comment]
Shall I just add an Implementation note to this effect - that this is more useful information that could be in the storage root/documentation object.

**Comment by awoods** [comment]
Closing as will-not-do.
