### ISSUE TITLE
Should we have a versions object indexed by version directory?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#231]
At present we have a `versions` array that has an object for each version. This leads to questions about the ordering of the items in that array (cf. #218, #220).  Should we instead have a `versions` object that is keyed by the version directory, with the value of `head` providing a pointer in to the key of the latest version:

```
{
  ...
  "head": "v2",      
  "versions": {
    "v1": { ...stuff for v1... },
    "v2": { ...stuff for v2... }
  }
}
```

**Comment by ahankinson** [comment]
+1 that sounds like a good idea

**Comment by awoods** [comment]
@zimeon : The suggestion sounds good. In your opinion, does it have any effect on the ordering question?

**Comment by ahankinson** [comment]
We can't support version ordering if we use a JSON Object, since they're assumed to be unordered.

I know ujson will not do anything to preserve ordering, and will change ordering of objects it reads in: https://github.com/esnme/ultrajson/issues/55

**Comment by zimeon** [comment]
I agree that if `versions` is an object then the content is semantically unordered by definition, it just has keys

**Comment by zimeon** [comment]
I think I am in favor of versions object over versions array. It seems cleaner and avoid questions about arbitrary ordering, we know the keys must always be nice clean values as they must match `r'''^v\d+$'''`, and when I think about using the data it leads to cleaner code.

**Comment by neilsjefferies** [comment]
I prefer object too
