### ISSUE TITLE
Release Alpha 0.1

### ISSUE THREAD

**Issue by awoods** [OCFL/spec#238]
* [x] get alpha spec up (#239)
  * [x] fix schema (#241)
  * [x] add links on homepage (#244)
  * [x] make announcements

**Comment by zimeon** [comment]
#239 still needs approval from @julianmorley and @neilsjefferies

**Comment by zimeon** [comment]
yup, I updated the checklist at top

**Comment by neilsjefferies** [comment]
OK

**Comment by awoods** [comment]
Resolved: https://groups.google.com/d/msg/ocfl-community/BB6anEmITEg/icN1mMe-BAAJ
