### ISSUE TITLE
Digest sidecar content: "name of inventory digest file" is just last element on path?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#242]
I think we intended to require:

```
adadadadadada..ff inventory.json
```

and not

```
adadadadadada..ff some/path/here/inventory.json
```

but we could perhaps spell that out more clearly in:

> The digest sidecar file MUST contain the digest of the inventory file. This MUST follow the format `DIGEST inventory.json`; that is, the digest of the inventory file, a single space, and the name of the inventory file.

by adding something like "without any preceding directory path".

**Comment by ahankinson** [comment]
'without any preceding directory path' seems like we're recommending stripping the path off; I think it's probably more precise (if not more succinct) to say that the path given in the sidecar file is relative to the path of the sidecar file itself.

**Comment by zimeon** [comment]
I was just about to make a PR added "relative to the path of the sidecar file" but then that would seem to admit `./inventory.json` which we also don't want. We want exactly `inventory.json` and nothing else.

**Comment by ahankinson** [comment]
👍

**Comment by zimeon** [comment]
maybe:

> ... that is, the digest of the inventory file, a single space, and the string `inventory.json` which is the name of the inventory file.

**Comment by ahankinson** [comment]
Do we need to make it obvious which one is THE inventory file, as opposed to AN inventory file (since they will be littered around the object)?

**Comment by zimeon** [comment]
could expand to:

> ... that is, the digest of the inventory file, a single space, and the string `inventory.json` which is the name of the inventory file in that directory.

**Comment by zimeon** [comment]
or _the same directory_.
