### ISSUE TITLE
Re-organize implementation notes

### ISSUE THREAD

**Issue by ahankinson** [OCFL/spec#245]
The Implementation notes are currently organized as all H1s. We should start to group these into logical sections. Perhaps:

* Digital Preservation
  * Rebuildability
  * Fixity
* Storage
  * Block size (small files)
  * Paths and restrictions
* Client Behaviours
  * Basic file operations
  * Versioning
    * Numbering
    * Order-of-operations
  * Purging files
  * Logging
  * Forward Deltas

[edit: updated to reflect comments]

**Comment by zimeon** [comment]
I agree that more structure would be good. In the list above I might put the "Digital Preservation" items first

**Comment by neilsjefferies** [comment]
Good idea. I think DP, the Storage Considerations, then Client Behaviours.

**Comment by ahankinson** [comment]
I've updated the first post to the latest suggested structure.

**Comment by awoods** [comment]
I agree that categorizing the elements would be helpful. We can probably go back and forth on the exact nature of the categories and the elements therein. 
For example, I would put `Version Immutability` and potentially `File Purging` under "Digital Preservation"... and I am not sure what `Versioning: Order of Operations` refers to.

That said, I would support an initial categorization, with the expectation that it will continue to evolve.

**Comment by ahankinson** [comment]
Client behaviours will require a certain sequence of operations for creating a new version to help ensure consistency of writes. For example, that inventories should be copied to the root as the last operation as an inventory in the root that does not contain the latest version info is a signal that there was an incomplete versioning operation.

On 19 Oct 2018, at 14:51, Andrew Woods <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree that categorizing the elements would be helpful. We can probably go back and forth on the exact nature of the categories and the elements therein.
For example, I would put Version Immutability and potentially File Purging under "Digital Preservation"... and I am not sure what Versioning: Order of Operations refers to.

That said, I would support an initial categorization, with the expectation that it will continue to evolve.
