### ISSUE TITLE
Requirements for inventory.jsonld

### ISSUE THREAD

**Issue by awoods** [OCFL/spec#26]
1. Forward-delta versioning
1. Manifest of each version's contents
1. Fixity data for de-duplication
1. Use of original filenames
1. Versions in separate data buckets
1. Support for file renaming
1. Support for duplicate files
1. Support for multiple locations (local and remote) within a version? - _in scope?_

**Comment by ahankinson** [comment]
re: #7: Duplicate by hash but not by filename? Duplicate by filename but not by hash? Or duplicate by both filename and hash, but not path?

**Comment by awoods** [comment]
Since we need to support the range of real-world use cases, I agree, supporting all variations of duplication makes sense. We should enumerate the possibilities for file duplication within a version and across versions.

**Comment by zimeon** [comment]
See also #29 -- digest of inventory in accompanying file
