### ISSUE TITLE
Add versioning to NEED

### ISSUE THREAD

**Issue by ahankinson** [OCFL/spec#264]
From e-mail feedback:

"Need: I was surprised that versioning wasn't mentioned in the Need statement, given that it is one of the key aspects of the spec and of its predecessor, Moab. It also is perhaps one of the most distinguishing differences from BagIt. I think this ends up underselling the spec a bit since having a standard way of structuring version directories is a key reason to adopt it. "

**Comment by zimeon** [comment]
I very much agree with this feedback from Sibyl Schaefer, certainly I argue that this is a key motivation for OCFL
