### ISSUE TITLE
Clarify contents of Storage Root

### ISSUE THREAD

**Issue by ahankinson** [OCFL/spec#267]
From slack feedback:

"Is there a contradiction between "An OCFL Storage Root MUST NOT contain any files or directories other than those described here" and "The behavior of the storage root may be extended to support features from other specifications. An OCFL validator MUST ignore any files in the storage root it does not understand"? So, for instance, my pairtree_version0_1 file in the example above seems to run afoul of the first but is okay with the second."

**Comment by zimeon** [comment]
I think the first statement quoted is the error -- other files MAY be present in the storage root and MUST be ignored if not understood
