### ISSUE TITLE
Style: "the OCFL" or "OCFL"?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#270]
PR #269 proposes a change from saying "OCFL" as if it were a word, to "the OCFL" understood as the acronym for "the Oxford Common File Layout". If this change were adopted then we'd need also to make corresponding changes in the implementation notes (e.g. "A key goal of OCFL is the rebuildability.." -> "A key goal of the OCFL is the rebuildability...") so we should make a general decision.

**Comment by zimeon** [comment]
I'm not sure that we want to say "the OCFL" everywhere. I'm fine with "the OCFL initiative" but would otherwise just say "OCFL".

**Comment by ahankinson** [comment]
I guess it depends. "A key goal of Oxford Common File Layout is the..." is grammatically wrong. However, "A key goal of **the** Oxford Common File Layout is the..." may not be, if it's understood that it's a goal of the specific file layout we are proposing. 

Based on a cursory glance, it seems the style is for initialisms usually get a definite article, while acronyms do not. "NASA launched..." vs. "The FBI sought..."

**Comment by ahankinson** [comment]
https://english.stackexchange.com/questions/30596/using-the-definite-article-with-acronyms-and-initialisms for reference

**Comment by awoods** [comment]
I am happy to defer to the grammatical rules, but in reading the spec, the phrasing of ".. the OCFL .." strikes me as odd.

**Comment by zimeon** [comment]
Discussed in editors' meeting and in community meeting: Agreement that we will use **"the OCFL"** everywhere.
