### ISSUE TITLE
Describe significance of user field

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#274]
Comment about user data split from @justinlittman #272:

  * In 3.5.3, describe the significance of the user field.

**Comment by zimeon** [comment]
I agree that we do not provide sufficient motivation for the requirement of the [`user` field](https://ocfl.io/0.1/spec/#version) (does it really justify MUST?) and its format

**Comment by rosy1280** [comment]
@zimeon would it make sense to split out the list into two sections, must and may? I can see the message being in a similar boat as user.
