### ISSUE TITLE
digest/file state maps -- wrong direction?

### ISSUE THREAD

**Issue by bdwheele** [OCFL/spec#277]
First off, if I've missed something obvious, go ahead and ignore me :)

What is the rationale for having the state maps with digest being digest -> array of paths? 

That seems backward to me, as the paths have to be unique in the filesystem namespace.  With this structure, it seems like it would be easy to construct an invalid map (either accidentally or maliciously):

"state": {
    "12345": [ "foo.bar", "readme.txt"],
    "53533": [ "foo.bar"],
}

Since there can't be two files named "foo.bar", then whichever of those entries were processed last would be the file that appears in the package. 

"state": {
   "foo.bar": "53533",
   "readme.txt": "12345",
}

**Comment by bdwheele** [comment]
Thanks for your response. 

The benefits of having a reduction of digest keys due to duplication seems limited, since beyond an empty file, there's probably not a lot of content that has the same digest.  I'm not sure what the odds are for collisions, although they could happen.  That means that for 99+% of the time, there's an array with a single item as the value for a given key.  

Likewise, having a hashing-friendly keyspace may very well be offset by the fact that in very large data sets (such as a series of DPX frames or a book with many pages), the filenames would have fairly consistent naming ("Frame-0000001.dpx", etc) so would be friendly...ish

I suspect that one of the most common operations on a given state would be to get the list of filenames.  With the current structure, that's a computationally expensive operation:
````python
files = []
for k in ocfl['versions']['v1']['state'].keys():
    files.extend(ocfl['versions']['v1']['state'][k])
````
With the downside that if one were checking for errors, a file name could appear more than once and it would have to be dealt with.

If the keys are the file paths, then the operation is dead simple (and likely much faster when there are 10's of thousands of files):
````python
files = ocfl['versions']['v1']['state'].keys()
````
While there are other ways to do this, replacing a file also looks to be more computationally expensive:
* Copy the previous state 
* search the state structure to find the digestkey for the name you're looking for
* remove the name you're looking for from the array in the state structure with the digestkey you found
* add the new file either to an existing digestkey array in the state, or make a new one

Compared to just setting the value of the (existing, because we're replacing) filename key to the digest.

**Comment by rosy1280** [comment]
perhaps we should discuss this in an OCFL article

**Comment by ahankinson** [comment]
Discussed on the 05/12/2018 editor's call. Decision was that this has been discussed at length, and even included in some previous drafts of the spec. 

The reason we chose to do hash/array of values is related to #275 in that arbitrary input as key values (filenames from unknown sources), while mostly stable, do have the possibility to break addressability within the object when transitioning between filesystem encodings and JSON.

The 'malicious' angle is an important one, and thank you for bringing it up. If, however, someone has access to muck about with the inventory, they can just as easily replace the hash:

```
state: {
  "foo.bar": "53533",  - change -> "foo.bar": "12345"
  "readme.txt": "12345",
}
```

to the same effect.

The decision was to keep the ordering as hash/array of paths. Thank you for taking the time to write up your suggestion, @bdwheele .
