### ISSUE TITLE
OCFL Elevator Pitch

### ISSUE THREAD

**Issue by awoods** [OCFL/spec#278]
We should establish a concise "elevator pitch" for OCFL, likely based on the ["Need" section](https://ocfl.io/0.1/spec/#need).

**Comment by rosy1280** [comment]
How about something like: OCFL is an application independent way of storing versioned digital objects.

**Comment by awoods** [comment]
@rosy1280 : "...with a focus on long term digital preservation."

**Comment by rosy1280** [comment]
> The OCFL represents a specification of the community’s collective recommendations addressing five primary requirements: 1) completeness, so that a repository can be rebuilt from the files it stores, 2) parsability, both by humans and machines, to ensure content can be understood in the absence of original software, 3) robustness against errors, corruption, and migration between storage technologies, 4) versioning, so repositories can update and make changes to objects that allow the history of the object to persist, and 5) ability to store content on various storage infrastructures including cloud object stores.

**Comment by awoods** [comment]
Bursting 1<a href="https://dura-videos.s3.amazonaws.com/20190614_hand_2014.png"><img src="https://dura-videos.s3.amazonaws.com/20190614_hand_2014.png" width="196" title="bursting 1"></img></a>
