### ISSUE TITLE
Object specification definition - revision suggestion

### ISSUE THREAD

**Issue by peterVG** [OCFL/spec#28]
We discussed the definition for Objects in today's community call. It was suggested to move this to GH as a next step. I'm not able to branch and pr on the repo atm so I will post this as an issue here instead. The following captures the changes I had suggested to put the emphasis back on the concept of "files" in the primary specification definition. I'll leave it to the spec editors to do with as you please:

3. Object Specification
"An OCFL Object is a group of one or more content and metadata files (e.g. file1.jpg, file2.txt, file3.ead.xml, file4.dc.json). This object is identified by an URI and includes OCFL administrative information. This administrative information may contain a sequence of versions of the files that document the evolution of the object's contents. The files in the object follow a layout as prescribed by the OCFL specification."

**Comment by SibylSchaefer** [comment]
Regarding the last sentence: is it the files in the object that follow the OCFL layout, or the versions of the object which do? My understanding was the latter.

**Comment by peterVG** [comment]
My understanding from reading the OCFL background paper is that it is both. E.g. "Object versioning is implemented using a folder hierarchy within the digital object’s root directory"
https://docs.google.com/document/d/13gFfSu1fePKx0eQYk458zE6OZwCW5JH_hTIG58f3S8c/edit) The way I read it, OCFL specifies how to include versions of an object as well as all other content, metadata, and administrative information (eg. .logs, versions.jsonld) about that object. So maybe the  last sentence could be changed to "The files in the object, along with information about any of its versions, follow a layout prescribed by the OCFL."
I am not authenticated to make PRs in this repo so I'll leave it to someone else to put the request in formally if it is deemed worthwhile. I am kind of parachuting into this existing territory so I certainly don't want to make any unsubstantiated comments that unsettles prior work. I was just following up on the request to document the discussion as an interested third-party and the comment on the role of "files" in the definition.

**Comment by zimeon** [comment]
My understanding of the reason to talk about bitstreams rather than files was to make it clearer that we cover things in object stores (such as S3) rather than just filesystems. Having said that, one can either write a general definition and then later talk about implementation on a filesystem or object store, or could write a slightly over-specific definition and then generalize later by says it could also work on object stores.

Either way, I think it would be a mistake to put example file/object names, especially ones with some suggested meanings based on implicit extension typing, in the definition.

**Comment by peterVG** [comment]
Yes, I see from the list of Use Case issues that object storage like S3 is explicitly in scope so my (roughly worded) suggestions for definition revision would be taking things in the wrong direction, sorry. I needed to realize that it is called the "oxford common *file* layout" and not "*filesystem* layout." If anything this discussion is a good reminder of that. I'm not directly involved in the spec writing but I think you're initial suggestion to keep the definition general (as it stands now) makes it easier to continue your use case scoping work, rather than word-smithing an overly narrow, possibly-incorrect definition before your scoping work is done. That said, and this was the initial comment all along, it still seems a little weird not to have the word "file" somewhere in the definition.

**Comment by zimeon** [comment]
We have addressed the main issue here by not relying solely on the notion of bitstreams but instead talking about files. Additional work on section 2 is adding relevant definitions.

**Comment by rosy1280** [comment]
closed.  see #133
