### ISSUE TITLE
Tighten wording around version numbering

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#281]
Suggestion from John Kunze via https://groups.google.com/d/msg/ocfl-community/l5Ql1jD7PMg/IzgiI0H0BQAJ :

This is a proposed change (original wording below it) to the format of version directory naming. It's designed to clarify and strengthen the spec around leading zeroes in version numbers.

--- proposed new wording ---
> The sequence of version numbers is taken from the sequence of positive, base-ten integers, 1, 2, 3, etc., and a given version directory name can be constructed from the letter v followed by the version number, for example, v1, v2, v3, etc. 
>
> For usability in the face of common lexical sorting tools (such as Unix ls) while maintaining predictability in directory names, an initial set of version numbers, starting with the first (ie, the lowest extant version, numerically speaking), may be zero-padded. In this case, assuming that the first version that is padded with zeroes has N+1 digits (eg, 001 for N=2), the following conditions must hold: (a) all version numbers less than 10^N are zero-padded to N+1 digits (eg, 001, ..., 009, 010, ..., 199 for N=2) and (b) all version numbers greater than or equal to 10^N are not zero padded. [Possibly an edge case, note that N can be determined even if the original first 10^N-1 version directories are missing, provided the lowest extant version (eg, v099) is zero-padded.]

--- original wording ---
> The sequence of version numbers is the sequence of positive integers: 1, 2, 3, etc., and the version directory name is constructed by adding the prefix v. Implementations should use version directory names constructed without zero-padding the version number, ie. v1, v2, v3, etc..
> 
> For compatibility with existing filesystem conventions, implementations may use zero-padded version directory numbers, with the following restriction: If zero-padded version directory numbers are used then they must start with the prefix v and then a zero. For example, in an implementation that uses five digits for version directory names then v00001 to v09999 are allowed, v10000 is not allowed.
>
> The first version of an object defines the naming convention for all version directories for the object. All version directories of an object must use the same naming convention: either a non-padded version directory number, or a zero-padded version directory number of consistent length. Operations that add a new version to an object must follow the version directory naming convention established by earlier versions. In all cases, references to files inside version directories from inventory files must use the actual version directory names.

**Comment by zimeon** [comment]
Picking the suggestion apart a bit:
  * adds "base-ten" to clarify what we mean by integer representation (good I think)
  * adds reference to Unix `ls` command (I think I'd prefer to keep such things in the implementation notes)
  * removes the recommendation to avoid zero padding and motivates use of zero padding for lexical sorting rather than compatibility  (I would prefer to recommend **not** zero-padding which is where we landed in #2 )
  * makes less clear the requirement that all versions use the same naming convention  (I think we'd need to add that back)
  * introduces more mathematical description of numbering strategy/limits (not sure about clarity/readability trade-off)

**Comment by ahankinson** [comment]
For version directory names, the background discussion we had is here: https://github.com/OCFL/spec/issues/2

The consensus we landed on was that there is a use case for both integer and lexically-oriented version names, so we should not change this decision.

**Comment by rosy1280** [comment]
in the bulleted list @zimeon references above, i would vote for including the first bullet point.

as a member of the editorial team that originally argued for zero padding, i no longer see its necessity, so i would say let's not rehash old decisions.  

i think the remaining bullet points make the spec less clear/readable so i would argue not to include them.

**Comment by awoods** [comment]
Reflecting on the distillation provided in @zimeon 's [comment](https://github.com/OCFL/spec/issues/281#issuecomment-441100958), I would suggest updating the comment to use numbers in place of bullets, and I agree with the conclusions:
- Add "base-ten" clarification
- Add Unix `ls` discussion to [implementation-notes](https://ocfl.io/draft/implementation-notes/)
- No other changes
