### ISSUE TITLE
UTF Encoding for OCFL

### ISSUE THREAD

**Issue by rosy1280** [OCFL/spec#284]
see: https://github.com/OCFL/spec/pull/227#discussion-diff-224943314R374 for more discussion

**Comment by zimeon** [comment]
Proposal from editors' call. In the specification we will add comment that:
  1. The inventory, as JSON, is in UTF
   2. The OCFL relies upon a storage layer (filesystem or object store) that consistently and unambiguously maps unicode pathnames in the inventory files/objects.

**Comment by zimeon** [comment]
Editors' call: #317 didn't add anything explicit about UTF but we have decided that we don't need to mention it explicitly. JSON is already clearly defined over UTF
