### ISSUE TITLE
Case sensitivity and OCFL

### ISSUE THREAD

**Issue by rosy1280** [OCFL/spec#285]
Should go in the Spec. See: https://github.com/OCFL/spec/pull/227#discussion-diff-224908719R375

**Comment by awoods** [comment]
What is the exact suggestion in this issue?

**Comment by neilsjefferies** [comment]
OCFL requires case sensetivity and case preservation. Not supported on file systems that can't manage that.

Hard statement in spec and admit that it can be done with caveats in Imp Notes.

**Comment by zimeon** [comment]
This does not appear to have been addressed in #317. We could add a bullet point to [Filesystem Feature](https://ocfl.io/draft/spec/#filesystem-features) along the lines of:

|  * File paths and filenames in the OCFL are cases sensitive. Filesystems MUST preserve the case of OCFL file paths and filenames.
