### ISSUE TITLE
Places to contact re: OCFL Beta release

### ISSUE THREAD

**Issue by rosy1280** [OCFL/spec#287]
Start creating a list of institutions.

**Comment by rosy1280** [comment]
OR 2019 presentation

**Comment by awoods** [comment]
* University of Wisconsin, Madison
* Notre Dame

**Comment by rosy1280** [comment]
Listservs:
* PASIG
* Fedora
* Code4Lib
* Samvera
* Islandora
* DSpace
* Educause Lib-IT

**Comment by rosy1280** [comment]
@awoods we need an email to the listservs identified above so we can land beta on June 4th.  we have assigned that ticket to you. :)

**Comment by awoods** [comment]
Resolved with: https://groups.google.com/d/msg/ocfl-community/3II6e92kRdw/AF1u-asfBwAJ
