### ISSUE TITLE
Clarify how to extend algorithm choices

### ISSUE THREAD

**Issue by ahankinson** [OCFL/spec#292]
From the [2018.11.07 Editor's Meeting](https://github.com/OCFL/spec/wiki/2018.11.07-Editors-Meeting)

"We note that tools reading OCFL objects do not need to understand the digest algorithm used for content addressing in order to get any version. Understanding of the digest algorithm is needed for validation or write operations... Will create new issue to discuss how we support extension beyond digests listed in the table"

**Comment by awoods** [comment]
One option is to include new algorithms in subsequent releases of the specification. Another approach is to allow implementations to note in their inventory.json files whichever algorithms they use, and require the validation tooling to either understand the noted algorithm, or fail the validation.

**Comment by zimeon** [comment]
See previous discussion in #21 . IMO, the key function of the table is to be a registry that maps strings (like 'sha1') to a description of the algorithm and encoding. Currently, a spec update is required to add something.

**Comment by zimeon** [comment]
I think that, for now at least, we have decided that we'll update the spec to include new algorithms. I'm OK with that for beta/1.0 though I think longer term it should be addressed differently. I propose close won't fix

**Comment by ahankinson** [comment]
Will be addressed with #371

**Comment by ahankinson** [comment]
Fixed now.
