### ISSUE TITLE
Add inventory file for each version of an object

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#3]
From [2018-03-28 meeting notes](https://docs.google.com/document/d/1UOEdzNqh59SSstWw78HblLQPSfqB_A55ci1tVeZkq1Y/edit#) there was a "decision" to add an inventory file to each version directory and some discussion of whether the top-level version information would be reconstructable from these inventories:

> * Moab vs OCFL
>   * Moab never changes files;  you only add files via new versions.
>     * You have to look at more files to get to all the content in a particular version
>     * You don’t duplicate storage
>   * OCFL versions:   the only metadata about the distinctions b/t versions is in versions.jsonld
>   * Moab has manifests directory for each version;  OCFL does not have that (and especially not the file diff info as a manifest)
>   * Should OCFL have forward versioning manifest info for each version?
>   * OCFL is sha256; currently baked in;  meant for de-dup, not fixity checking
>   * Reconstituting versions.jsonld is crucial to reconstituting the object
>   * Decision?  Add inventory.jsonld to the top level of each version subdirectory
>
> ...
> Decisions
> ...
> * Add relevant inventory.jsonld to the top level of each version subdirectory
> * Also add [sha256].sha256 (sha of inventory.jsonld) to each version directory?

**Comment by zimeon** [comment]
I favor having an `inventory.jsonld.sha512` inside each version directory. This can be written as soon as the `inventory.jsonld` has been finalized and makes the versions somewhat more self-contained in the sense that between `inventory.jsonld` and `inventory.jsonld.sha512` there is a checksum for every data file included under the version directory. Such abilities would be very clean if used in a system that transferred new versions about and then verified transmission fixity for just the new data in each version

**Comment by zimeon** [comment]
Per #21 where we have agreement to recommend `sha512` but allow other algorithms, I think we can resolve this issue with:
  * agree that there is an `inventory.jsonld` in the top level dir of each version
  * agree that there must be at least one checksum sidecar `inventory.jsonld.CHECKSUM` for the inventory file

**Comment by ahankinson** [comment]
Done and written in the spec. Closing.
