### ISSUE TITLE
Should OCFL be defined in terms of files or bitstreams?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#30]
The current definition of an [OCFL object](https://ocfl.io/#object-spec) says:

> An OCFL Object is a group of one or more content bitstreams (data and metadata), and their administrative information that are together identified by a URI. The object may contain a sequence of versions of the bitstreams that represent the evolution of the object's contents.

If the name of the initiative/spec includes file in the title, should we include file in the definition of an OCFL object? If so, how do we indicate that this work can be generalized to work over object stores too?

**Comment by awoods** [comment]
I can see using "file" in the above definition, then having a footnote (or subsequent definition) stating that a "file" can include any persisted bitstream.

**Comment by zimeon** [comment]
:+1: - I think that would be a reasonable resolution of the issue

**Comment by zimeon** [comment]
I note that this while talking about file<->bitstream we might also mention directory<->path-segment

**Comment by zimeon** [comment]
Addressed by #44 and #97, also related to #28
