### ISSUE TITLE
Clarify the value of 'head' with a MUST

### ISSUE THREAD

**Issue by ahankinson** [OCFL/spec#303]
Currently we have:

"head: A value corresponding to the version directory name of the most recent version of the object."

I propose we change this to:

"head: A value which MUST correspond to the version directory name of the most recent version of the object."

This will clarify that the value of `head` cannot be a previous version.

**Comment by zimeon** [comment]
I don't think you can put normative spec in the terminology section. If we want to add a MUST then it should be somewhere else

**Comment by birkland** [comment]
In https://ocfl.io/draft/spec/#inventory-structure would make sense
