### ISSUE TITLE
Be explicit about version sequence requirements for OCFL Object validity

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#306]
Based on Slack discussion with Scott Prater I think the current text in [Version Directories](https://ocfl.io/draft/spec/#version-directories) _“The sequence of version numbers is the sequence of positive integers: 1, 2, 3, etc., and the version directory name is constructed by adding the prefix `v.`“_ is intended to imply that the sequence MUST start at 1 and MUST be continuous without missing integers in order to be valid.

i.e.
  * [v1], [v1, v2], [v1, v2, v3] -- all valid
  * [], [v2], [v1, v3] -- all NOT valid

While I can imagine use cases that might want currently invalid cases (build empty shell to start, transfer v2 to an archive as a valid OCFL object then merge, entirely delete v2 for some reason after making sure that v3 is still consistent -- for the three examples above) I don't think these are required for any of our current [in-scope use cases](https://github.com/OCFL/Use-Cases/issues?utf8=%E2%9C%93&q=is%3Aissue+-label%3A%22Confirmed%3A+Out-of-scope%22+).

We should tighten language to be explicit/clear though.

**Comment by awoods** [comment]
:+1: to tightening language around requiring:
- sequential, positive integers, starting with 1 and prefixed with "v".

**Comment by rosy1280** [comment]
@julianmorley Can you please look at this ticket?  Its about version numbering sequences and I seem to remember you have a use case that is counter to this.  If so, please provide information about that use case.

**Comment by zimeon** [comment]
Discussion on editors' call found only use cases related to distributed storage and transfer use cases (see e.g. https://github.com/OCFL/spec/issues/22, https://github.com/OCFL/Use-Cases/issues/28, https://github.com/OCFL/Use-Cases/issues/27) that would justify support for sets of versions that are not a complete sequence starting with 1. These use cases have been deferred until OCFL v2 discussion

**Comment by julianmorley** [comment]
Can we describe a validation process where the version directory of an object on a storage root is valid, but the overall object is not? I can see a use case where you might have one object spread across multiple local storage roots, with the sum of the versions yielding a complete, valid OCFL object but each specific object directory being incomplete. I agree that this use case is deep into v2 territory, but I don't want to have to significantly re-write the spec to take it into account; I'd rather have a layered approach to object validation that doesn't rule this out in v1. Something like:
:white_check_mark: This OCFL object directory contains only valid version directories. 
:negative_squared_cross_mark: This OCFL object directory contains a complete sequence of version directories starting at 1. 
:white_check_mark: The inventory.json in the object directory matches the inventory.json in the highest present version directory.

**Comment by awoods** [comment]
@julianmorley : I suppose we could change the following `MUST`s to `SHOULD`s:
```
...MUST start at 1 and MUST be continuous without missing integers in order to be valid.
```

**Comment by ahankinson** [comment]
@awoods I'm -1 to that. The point of the spec, as I see it, is to give us something firm to validate against. If we change these MUSTs to SHOULDs then we're ultimately making it more difficult to write a validator that can do anything but raise warnings.

**Comment by ahankinson** [comment]
@julianmorley the issue with distributed version directories is that they need to coalesce to some form of central inventory file. 

The storage paths (that is, those held in the `manifest` section) are ALWAYS relative to AN object root. What you're proposing is effectively an inventory that can reference multiple object roots, where any given file in the inventory may not be stored local to the current object root.

I can see that, in OCFLv2, we may beef up the storage root spec to provide a way of resolving multiple storage roots. If the object ID is kept the same, this may provide a way of resolving multiple version directories, but this seems pretty fragile to me.

If we were to do non-sequential numbers, then I would propose that we use millisecond-precision datestamps to differentiate 'newest' from 'oldest'. And, if we do this, we should replace serial integers with a hash of sorts. Then we're deep into "just use git" territory.

However, the point of sequential integers and a simpler versioning approach is to maintain human readability for content-on-disk. It certainly constrains the choice of technologies you can employ, but it also removes the core dependencies on these technologies to make sense of your content.

**Comment by rosy1280** [comment]
@julianmorley it seems like you're trying to find a way to say that perhaps your forthcoming implementation is almost valid, i.e. the version directories meet acceptance criteria, but your object directories don't.  I can understand that.  

Right now the spec identifies criteria that would validate a single version directory in section 3.3 https://ocfl.io/draft/spec/#version-directories. There is then separate criteria validating the object.  Are you looking for the spec to contain something more specific?

**Comment by julianmorley** [comment]
I think the spec is probably fine... this could just be a validator issue. 

How about if we say that a validator *may* be provided with multiple storage roots, and if so, an OCFL object is valid if the validator can construct a full sequence of valid version directories from anything it finds on any root? If you only provide the validator with a single root, then an OCFL directory with incomplete version sequences isn't valid. 

Then we can defer implementation of multiple storage root validation to later.

**Comment by zimeon** [comment]
I think that saying anything about the possibility of objects spread across multiple storage roots is _out of scope_ for OCFLv1. To me that also means that any object that has a version `state` block that refers to a file not present in the object should be not valid per OCFLv1.

I remain open to having holes in the integer version sequence provided the object is still internally fully consistent, but maybe this does not provide a useful stop towards @julianmorley's distributed versions use case. (Which is think we should explore in v2.)

**Comment by awoods** [comment]
Without diving too far into the OCFLv2 hole, it is conceivable that there be local and remote version directories. 
- Local version directories are what we are specifying in OCFLv1
- Remote version directories also exist in the ocfl:Object, but contain a reference to another location.

In both cases, we retain the requirement that there be a sequential set of version directories.

**Comment by rosy1280** [comment]
We agreed (including @julianmorley ) that we would go with @zimeon 's original recommendations, sequential starting with v1 and incrementing up.  So the next version of the spec will handle distributed versions.
