### ISSUE TITLE
Consider changing existing file path to something else

### ISSUE THREAD

**Issue by rosy1280** [OCFL/spec#313]
I've noticed that folks continue to call existing file path by another name.  Should we consider changing the term to storage file path or physical file path.

**Comment by ahankinson** [comment]
Storage file path is a possibility. “Physical” implies an actual physical object to me, which is perhaps not accurate in a digital context.

**Comment by rosy1280** [comment]
Agreed. I note physical because I keep seeing folks refer to it that way. But then in the article @dbrower used storage path which seemed like a better fit.

**Comment by zimeon** [comment]
I see _physical_ as the usual opposite of _logical_ but I agree with @ahankinson that it seems to conjure the wrong impression. On balance I like **storage path** and **logical path**, and prefer them without the _file_ because then we avoid always sounding like a filesystem as opposed to some other storage system (like S3), and avoid saying file twice in various sentences. To take an [example sentence](https://ocfl.io/draft/spec/#manifest), we might then change:

> The value for each key is an array containing the **existing file paths** of files in the OCFL Object that have content with the given digest.

to

> The value for each key is an array containing the **storage paths** of files in the OCFL Object that have content with the given digest.

**Comment by birkland** [comment]
"storage path" seems like a more universally understood metaphor between the world of byte wrangling software engineers and librarians/archivists.   It reads well in the proposed language, and aligns well with the term "storage root"

**Comment by awoods** [comment]
+1 to "storage path"

**Comment by ahankinson** [comment]
Does it align too well with "storage root"? As in, are people likely to get confused that there is the storage root, and then a bunch of stuff in the middle that doesn't have a name, and then an object root, and then within the object root... a storage path?

**Comment by rosy1280** [comment]
@ahankinson that's a great point, but i think on the whole, folks are more likely to not use the storage root terminology as frequently as the storage path terminology (based on documents i've seen and conversations i've had so far).

**Comment by ahankinson** [comment]
Editors call 2019-03-06: Debated storage path terminology.

Decision: "existing file path" should change to "content path" in the documentation, and "logical file path" should be normalized to "logical path".

**Comment by zimeon** [comment]
This still needs a PR to make the terminology changes in the implementation notes (#333 fixed in spec)
