### ISSUE TITLE
Empty content folder: possible inconsistency between spec and example

### ISSUE THREAD

**Issue by eocarragain** [OCFL/spec#314]
Hi,
Section 3.3 of draft sepc (https://ocfl.io/draft/spec/#version-directories) states "Version directories must have a sub-directory called content if there are files present, and should not contain a content sub-directory otherwise"

Later, the diagram of the "Versioned OCFL Object" example in section 5.2 shows an empty content sub-directory thanks to forward-delta versioning (https://ocfl.io/draft/spec/#example-versioned-object). 

This is kind of useful for illustration purposes, but I found it confusing especially since empty folders aren't supported in general

cheers

**Comment by awoods** [comment]
Thanks, @eocarragain .
It looks like the [example in 5.2](https://ocfl.io/draft/spec/#example-versioned-object) should be updated to remove the `content` directory in `v3`.

**Comment by zimeon** [comment]
Agreed, thanks @eocarragain !
