### ISSUE TITLE
Add note about empty directories in object stores

### ISSUE THREAD

**Issue by ahankinson** [OCFL/spec#322]
Object stores do not support empty directories, so we should point this out in the implementation notes.

**Comment by neilsjefferies** [comment]
Some object stores do - since they maintain filesystem namespaces. OCFL prohibits this anyway so does mentioning this add anything?

**Comment by rosy1280** [comment]
@ahankinson is this still a ticket we need to address?

**Comment by zimeon** [comment]
This is already covered by the section https://ocfl.io/0.3/implementation-notes/#empty-directories
