### ISSUE TITLE
OCFL spec in text format?

### ISSUE THREAD

**Issue by tomwrobel** [OCFL/spec#328]
Hi All

Apologies if this has been asked before, but I'm hand creating a sample ORA object (or 2) in OCFL and I wanted to put them in a compliant storage root. I realise that it's optional, but including the OCFL spec in text format seemed like a good idea.

Is there a version of the OCFL spec in text format, that could be used as ocfl_1.0.txt? I've found quite a few sample objects, but no sample object roots.

By the way, our sample object root will be at https://github.com/tomwrobel/ora_data_model/tree/master/OCFL/storage_root for the time being.

Best wishes, and apologies if this is out of place

Tom

**Comment by awoods** [comment]
Hello @tomwrobel .
The decision from [2018.11.21-Editors-Meeting](https://github.com/OCFL/spec/wiki/2018.11.21-Editors-Meeting) was that an HTML version of the spec meets the need. See: https://github.com/OCFL/spec/issues/203

**Comment by tomwrobel** [comment]
@awoods Thank you, that's perfect.
