### ISSUE TITLE
sample inventory.json files do not validate against inventory_schema.json

### ISSUE THREAD

**Issue by tomwrobel** [OCFL/spec#335]
Dear All

[Apologies, and especially so if this should be raised in @zimeon's ocfl-py]

When I use the python jsonschema validator against inventory.json files (both my own and sample json files in the spec), I get an error:

```sh
https://ocfl.io/1.0/spec/#inventory: 'https://ocfl.io/1.0/spec/#inventory' is not one of ['Object']
```

**Comment by awoods** [comment]
I suspect the validator has not kept pace with changes in the spec. This does seem appropriate as an issue in [ocfl-py](https://github.com/zimeon/ocfl-py/issues).

**Comment by tomwrobel** [comment]
@awoods this isn't a validator issue, sorry if I wasn't clear. jsonschema is an independent library, and the Json schema is in the spec, not ocfl-py. The relevant command is:

```
jsonschema -i inventory.json /path/to/ocl/spec/draft/spec/inventory_schema.json
```

This error occurs with @birkland's inventory.json files, with my hand created ones, and with the sample ones included in the spec. The only reason for the link with @zimeon is that he has a page dedicated to discussing this.

I may be making a tit of myself here, but I don't think the inventory_schema.json file in the spec is correct in three places: 

https://github.com/OCFL/spec/blob/e750737f40476a54515eb0301add39fc3201de56/draft/spec/inventory_schema.json#L34

Should be

```
            "enum": ["https://ocfl.io/1.0/spec/#inventory"]
```

https://github.com/OCFL/spec/blob/e750737f40476a54515eb0301add39fc3201de56/draft/spec/inventory_schema.json#L55-L58 should be cut entirely (version does not require a type attribute)

and 

https://github.com/OCFL/spec/blob/e750737f40476a54515eb0301add39fc3201de56/draft/spec/inventory_schema.json#73 should be:

```
                    "required": [ "created", "message", "state", "user" ]
```

The patch file is as follows:

```git
diff --git a/draft/spec/inventory_schema.json b/draft/spec/inventory_schema.json
index f03eeeb..7a4f682 100644
--- a/draft/spec/inventory_schema.json
+++ b/draft/spec/inventory_schema.json
@@ -31,7 +31,7 @@
         },
         "type": {
             "description": "Seems that using `const` would be nicer but that doesn't seem to work with Python jsonschema",
-            "enum": [ "Object" ]
+            "enum": ["https://ocfl.io/1.0/spec/#inventory"]
         },
         "versions": {
             "description": "Each key is a version directory name with version objects as values",
@@ -52,10 +52,6 @@
                         "state": {
                             "$ref": "#/definitions/digests_to_files"
                         },
-                        "type": {
-                            "description": "Seems that using `const` would be nicer but that doesn't seem to work with Python jsonschema",
-                            "enum": [ "Version" ]
-                        },
                         "user": {
                             "type": "object",
                             "additionalProperties": false,
@@ -70,7 +66,7 @@
                             "required": [ "address", "name" ]
                         }
                     },
-                    "required": [ "created", "message", "state", "type", "user" ]
+                    "required": [ "created", "message", "state", "user" ]
                 }
             }
         }
```

**Comment by zimeon** [comment]
Thanks for your work on this @tomwrobel ! I agree that we (maybe me) had simply forgotten to keep this updated

**Comment by zimeon** [comment]
With the merges of #336 and #343 I think this issue is addressed, closing.
