### ISSUE TITLE
Add OCFL benefits to landing page

### ISSUE THREAD

**Issue by dwilcox** [OCFL/spec#344]
I recently presented on OCFL and included a slide summarizing the benefits (a copy of slide 13 from this presentation: https://docs.google.com/presentation/d/16jkDIhvkWx_5DU-X_e15xQuQTqgbO7W1mpmOt48ewxw/edit#slide=id.g546dde9be5_3_10). One of the attendees suggested that these benefits would be useful to capture on the landing page (https://ocfl.io). These are the benefits:

* Completeness, so that a repository can be rebuilt from the files it stores
* Parsability, both by humans and machines, to ensure content can be understood in the absence of original software
* Robustness against errors, corruption, and migration between storage technologies 
* Versioning, so repositories can make changes to objects allowing its history to persist 
* Storage diversity, to ensure content can be stored on diverse storage infrastructures including cloud object stores

**Comment by zimeon** [comment]
:+1:, thanks for suggesting @dwilcox
