### ISSUE TITLE
Use of RFC2119 language

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#35]
What words from [rfc2119](https://tools.ietf.org/html/rfc2119) will we use? Also need to add note and normative ref to spec.

**Comment by zimeon** [comment]
I note that there is an update https://tools.ietf.org/html/rfc8174

**Comment by zimeon** [comment]
I note that in the [Fedora API spec](https://fcrepo.github.io/fcrepo-specification/#conformance) we adopted only a subset of the RFC2119 keywords:

> The key words MAY, MUST, MUST NOT, SHOULD AND SHOULD NOT are to be interpreted as described in RFC2119.

**Comment by ahankinson** [comment]
From what I can tell, respec gathers these automatically and updates the docs accordingly.

Compare:

https://github.com/fcrepo/fcrepo-specification/blob/master/index.html#L111-L117

with 

https://fedora.info/2018/06/25/spec/#conformance

**Comment by zimeon** [comment]
Proposal from 2018-07-18 editors' call: we will limit ourselves to the minimal subset of MAY, MUST, MUST NOT, SHOULD and SHOULD NOT. We will avoid the variations such as RECOMMENDED which has the same weight as SHOULD per rfc2119. There is no need to add anything to the spec as reSpec automagically does this for us.

**Comment by zimeon** [comment]
Agreed: we will limit ourselves to the minimal subset of MAY, MUST, MUST NOT, SHOULD and SHOULD NOT
