### ISSUE TITLE
Clarifying purge operations

### ISSUE THREAD

**Issue by pwinckles** [OCFL/spec#369]
The File Purging section of the draft implementation notes contains the following text:

> The new object need not have the same identifier as the original object. In this case, the deleted object can be replaced by a "stub" object with the original identifier and location in the OCFL Storage Root. This object is a standard OCFL object that just contains brief information that redirects users and software to the new version - possibly with an indication of why the new object was created, if appropriate. The OCFL does not define this stub object in any way - its structure, interpretation and handling are entirely client dependent, but ideally some elements should be human readable for rebuildability.

What are the minimum required contents of a "stub" object?

According to section 4.3 of the spec, "Storage hierarchies MUST be terminated by OCFL Object Roots," which I take to mean that the stub object needs to be a valid OCFL Object Root. My reading of the spec suggests that this includes the following: 0=ocfl_object_1.0, inventory.json, inventory.json.sha512, and at least one version directory. Is that correct?

Are the implementation notes suggesting that the redirect information be stored in some structure within a version's content directory? If so, this seems to put OCFL clients in the awkward position of needing to inspect object content if they are interested in following a redirect to the new object.

Or, perhaps it's suggesting putting a file (structure undefined) in the object root to indicate the redirect? In this case, I presume that an empty version directory is still required.

This raises another question. @birkland and I were both operating under the assumption that undefined files and directories were not allowed under an object root. However, after reviewing the spec again just now, I failed to identify any language that supports this assumption. Is the intent to allow arbitrary files and directories under the object root?

One more thing. The text says, "The new object need not have the same identifier as the original object." What about the case where I want it to have the same identifier? This creates another awkward situation. I could construct a new object in the deposit directory, delete the original object, and move the new object into its place. I don't like this because it puts the object at risk of being lost between the delete and the move, and it creates a period of time when the object does not exists (the length of which is naturally dependent on how the move has to be implemented).

One idea I was considering today involved playing with how object ids are mapped to paths. For example, let's say the object id 'obj123' is mapped to 'ob/j1/23' but its object root is actually at 'ob/j1/23/1'. When a purge operation is performed, a copy of the object with the same id is created at 'ob/j1/23/2'. Once the new copy of the object is complete, 'ob/j1/23/1' is deleted. When accessing an object, the client first maps the object id to a path and then selects the directory under that path with the lowest number (unless it's in the middle of a copy there should only be one).

I know the OCFL spec does not have a position on layout. However, doing what I described above would temporarily create a situation where there are multiple OCFL objects with the same object id, which is forbidden. Is an approach like this not recommended? Is there a better way of doing this? If so, I think it would be valuable to have in the notes.

**Comment by neilsjefferies** [comment]
Partial respose to a couple of your questions....

Purge is a always a destructive operation. In the overwriting case, if the new object is created using the <code>deposit</code> directory and the order of operations described in the Implementation Notes is used then there should be no unrecoverable loss state for the new object. The old object is destructable by definition.   

OCFL requires the ID mapping to objects paths to be consistent so the creation of mutiple paths refering the the same ID should not occur. It would be a validation failure if it did.

OCFL does not specify the detail of a redirect object because it depends on the reason for the purge operation. 

The expectation is that OCFL content is going to be cached so that inspection of objects happens rarely - a redirect index mapping old/new ID's would be expected to exist in systems that support such operations. Maybe this should be expanded in the Notes.

**Comment by pwinckles** [comment]
To summarize what I'm hearing:

1. It's acceptable for an object to be temporarily unavailable during an overwrite purge operation when the original object root cannot be replaced by the new object root using a filesystem rename, so long as the object content is always recoverable.
1. OCFL requires ID => path mappings to be consistent. Can you point me to where the spec says this? I can't find it.
1. No comment yet on whether or not arbitrary files/directories are allowed within the object root.

> @neilsjefferies 
> 
> The expectation is that OCFL content is going to be cached so that inspection of objects happens rarely - a redirect index mapping old/new ID's would be expected to exist in systems that support such operations. Maybe this should be expanded in the Notes.

My issue here is that it seems like a violation of the separation of object content data from data about how the object is stored. It's fine if a user wants to add a file to the object content of a purged object that indicates to them in some meaningful way what happened. However, I think it's inappropriate for and OCFL library to treat object content as anything other than opaque. As such, if an OCFL library were to automatically resolve a redirection, the information would need to be stored outside of the object's content, such as in a file in the object root.

**Comment by neilsjefferies** [comment]
Hmmm, I think that is possibly a philosophical question for the whole Editorial team. Is a redirect content or OCFL metadata? I would not expect a low level client to resolve redirects but leave it to a higher level application. However, that is my opinion.

However, ithink we should be clear that purge operations do break OCFL assumptions and can't be done entirely safely.

**Comment by pwinckles** [comment]
Implementing a low-level client redirect certainly does open new problems. Can updates be made on the original object id? If so, do the updates apply to the original object or to the object that the original object redirects to?

My perspective is that I think you're probably right that redirects aren't something that should be resolved by a low-level OCFL client. However, the main reason that I would consider doing it is a) if I frequently need to rewrite objects to squash versions (depends on the outcome of #370) and b) there isn't a non-disruptive way to overwrite an object.

I still am very much interested in knowing:

1. Whether or not arbitrary files/directories are allowed in the object root? If the answer is yes, it makes it easier for an OCFL client to implement a low-level redirect if they are so inclined.
1. Whether or not ID => Path mappings must be consistent? If they don't need to be, it makes it easier to implement a non-disruptive object overwrite. That said, even if the spec doesn't allow it, I don't know how you could ever validate it.

**Comment by zimeon** [comment]
I think:
  1. the intention has been that additional files or directories are NOT allowed in the object root. However, I agree that this is not spelled out --> #373 
  2. my reading of [4.3 Storage Hierarchies](https://ocfl.io/0.3/spec/#root-hierarchies) "3. Storage hierarchies within the same OCFL Storage Root SHOULD use just one layout pattern" is that "... one layout pattern" is another way of saying "SHOULD have a consistent mapping"

**Comment by pwinckles** [comment]
> @zimeon 
> 
>     2. my reading of [4.3 Storage Hierarchies](https://ocfl.io/0.3/spec/#root-hierarchies) "3. Storage hierarchies within the same OCFL Storage Root SHOULD use just one layout pattern" is that "... one layout pattern" is another way of saying "SHOULD have a consistent mapping"

My reading of that is that a repository should not use both flat mapping and pairtree mapping, for example. To me, that's something different than saying that an id should always be mapped to the same path. The layout I described in my first post is an example of a way ids could be predictably mapped to paths, but the mapping would not be consistent.

**Comment by zimeon** [comment]
@pwinckles: I think not mixing flat/tree is bullet 4, but you have anyway demonstrated that the current text is not sufficiently clear --> #374

**Comment by rosy1280** [comment]
Question: do we support redirects?  
Answer: OCFL does not define redirects.  any implementation of redirects are part of the content of the object.  handling the content of the object is an access repository's concern.  

we need to update the implementation notes to make this clear.

**Comment by neilsjefferies** [comment]
Fixed by #380
