### ISSUE TITLE
Make it clear that it is expected to have a well defined bi-directional mapping between storage path and id

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#374]
The current text in [4.3 Storage Hierarchies](https://ocfl.io/0.3/spec/#root-hierarchies) does not spell out that we expect there to be a well-defined bi-directional mapping between id and storage paths such that for an id the path is uniquely defined, and vice versa. 

See https://github.com/OCFL/spec/issues/369#issuecomment-531680861 and following discussion

**Comment by rosy1280** [comment]
if we have the object id then you should be able to work out the storage path, but to go the other way is not required.

You MUST work out storage path knowing the object id, and you SHOULD be able to go the other way.

**Comment by pwinckles** [comment]
Recommending bi-directional mappings seems a little odd to me because it precludes hashing object ids, requiring the object ids themselves to be suitably random in order to avoid creating unbalanced trees.

**Comment by julianmorley** [comment]
> You MUST work out storage path knowing the object id, and you SHOULD be able to go the other way.

Change to:  You MUST work out storage path knowing the object id.
