### ISSUE TITLE
Rapid work and merge policy through to 2018-07-07 in person meeting

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#38]
Discussed on [2018-07-18 editors' call](https://github.com/OCFL/spec/wiki/2018.07.18-Editors'-Meeting), we propose the adopt the following policy in order to get more content up quickly before the in-person meeting:

> * UNTIL 2018-07-07 - A pull request should be merged a majority of editors have responded with 👍/+1, provided no editors have responded with 👎/-1, without any time delay requirement.

will add as extra bullet on https://github.com/OCFL/spec/wiki/Change-Suggestion-and-Resolution-Process

**Comment by rosy1280** [comment]
:+1:

**Comment by julianmorley** [comment]
👍

**Comment by ahankinson** [comment]
This was also approved by @neilsjefferies in a separate e-mail, so I have added this to the change resolution page. Closing.
