### ISSUE TITLE
Extract normative MUSTs and SHOULDs for validators

### ISSUE THREAD

**Issue by ahankinson** [OCFL/spec#384]
The spec should be reviewed for validated-able rules, see: https://github.com/OCFL/spec/wiki/OCFL-Validator-Codes

**Comment by rosy1280** [comment]
@ahankinson do you have a link to the MUSTs and/or SHOULDs?  I seem to remember seeing a list at some point.

**Comment by awoods** [comment]
@rosy1280 : In the course of updating the [OCFL Validator Codes](https://github.com/OCFL/spec/wiki/OCFL-Validator-Codes) wiki page, I was using the following grep-created document as guidance:
https://gist.github.com/awoods/b03bf5ec7e1f4c040c69cfd694f3921f

**Comment by julianmorley** [comment]
Here's what I've been using so far:
https://github.com/sul-dlss-labs/OCFL-Tools/blob/master/results_codes.md

**Comment by zimeon** [comment]
The codes currently used in my code are at https://github.com/zimeon/ocfl-py/blob/master/ocfl/data/validation-errors.json -- I will he happy to reconcile these with whatever canonical list we come up with
