### ISSUE TITLE
Promoting 1.0 release

### ISSUE THREAD

**Issue by rosy1280** [OCFL/spec#386]
- [x] Create [press release](https://docs.google.com/document/d/1pNteQqcBkrkNedu-AVLy0izSpWJiJFxtq96Wa9UHz6Q/edit#heading=h.s0jjuzddr985)
- [x] Identify email lists to send the press release to
- [ ] Create news directory within the ocfl.io site; create a news section on the main page that links to news page; all press releases will just be on a single page.
- [x] Update logo on: github, website, etc.

**Comment by rosy1280** [comment]
Stub for press release: https://docs.google.com/document/d/1pNteQqcBkrkNedu-AVLy0izSpWJiJFxtq96Wa9UHz6Q/edit

**Comment by rosy1280** [comment]
Stub for presentation: https://docs.google.com/document/d/1qxDwUYxVonRZISRnxeJ4z76UnIY1YpJQ_I0VWv7TU6E/edit

**Comment by neilsjefferies** [comment]
DPC are on board for a WDPD launch and blog post. Discussing possible timing for a PR shortly before.

**Comment by neilsjefferies** [comment]
Need to have posting for WDPD ready so we can get it queued up.

**Comment by rosy1280** [comment]
Press release and blog post have been combined.

**Comment by rosy1280** [comment]
i started a [list of email lists](https://docs.google.com/spreadsheets/d/1v2V5CTfuHO3oFFlJB5gDQu420b0hLtsUwmbOFEPvuP8/edit#gid=0) for publicizing the 1.0 release; I primarily took from a similar list we used when I was on the OR program committee.  it is by no means meant to be a definitive list so while i've already done some curation, feel free to add or remove lists. do try to think broadly around interest in the spec though, we want to cast a wide net.

**Comment by rosy1280** [comment]
remaining action item will be completed as #497
