### ISSUE TITLE
Deposit directory

### ISSUE THREAD

**Issue by ahankinson** [OCFL/spec#396]
Am I right in remembering that this paragraph:

> An OCFL Storage Root may contain a directory named deposit, which may be empty. Implementations may use this directory for assembling new or updated content. Clients performing any other operation, or validating a storage root, must ignore the deposit directory if present.

should now be removed from the spec?

**Comment by ahankinson** [comment]
And this one:

> Except for a deposit directory, sub-directories within an OCFL Storage Root must not contain files that are not part of an OCFL Object. Empty directories must not appear within a storage root.

**Comment by awoods** [comment]
Yes, my understanding is that we are removing the concept of an internal `deposit` directory.

**Comment by neilsjefferies** [comment]
Yes, mutable stuff should now reside outside the Storage Root and OCFL. Hence discussed in the Imp Notes, and only as an example.
