### ISSUE TITLE
Editorial policy - what is agreement? 

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#4]
We need to decide how we agree to move forward and decide an issue is resolved, and how we agree that a change should be merged and does indeed reflect the decision. The best experiences I've had with such processed are in IIIF and the Fedora API (both a similar size editorial group, 5 instead of 6).

  * [IIIF Editorial Process](http://iiif.io/api/annex/notes/editors/) - discuss in community, hope to reach community consensus, editorial discretion as to when that has occurred. Within editors' group: all but one editors +1, no -1 for normative change (see: [Acceptance Criteria for Merging Changes](http://iiif.io/api/annex/notes/editors/#acceptance-criteria-for-merging-changes))
  * Fedora API [Issue Resolution Process](https://github.com/fcrepo/fcrepo-specification/wiki/Issue-Resolution-Process) - all editors +1 or majority editors +1, no -1 after 72 hours.

**Comment by zimeon** [comment]
I propose that OCFL should adopt for [Fedora API Issue Resolution Process](https://github.com/fcrepo/fcrepo-specification/wiki/Issue-Resolution-Process) for making changes to the spec. With 6 editors this will mean 4 +1, no -1 to merge after 72 hours.

I think @ahankinson's proposed process for [managing use cases](https://github.com/OCFL/Use-Cases/wiki) in a lightweight way (2 eds agree, hopefully as a reflection of community agreement) is fine when there is a stronger gating on the spec updates (if we can't agree to the update then we can always go back to revisit the use cases).

**Comment by ahankinson** [comment]
Sounds good to me. It *will* require editors to be on the ball about checking their GH issues, though.

**Comment by awoods** [comment]
In addition to agreeing with https://github.com/OCFL/spec/issues/4#issuecomment-378413908 , I would suggest that we relax any pull-request/merge policy initially to populate critical mass of content.

**Comment by awoods** [comment]
Apropos my previous comment, when do we know we have reached "critical mass of content"?

**Comment by ahankinson** [comment]
@zimeon will appropriate the fedora spec for our wiki page

**Comment by zimeon** [comment]
Have created a wiki page describing out [Change Suggestion and Resolution Process](https://github.com/OCFL/spec/wiki/Change-Suggestion-and-Resolution-Process) complete with handy-dandy links into the issue tracker

**Comment by awoods** [comment]
@zimeon / @rosy1280 : [The policy](https://github.com/OCFL/spec/wiki/Change-Suggestion-and-Resolution-Process) looks good. :+1:

**Comment by zimeon** [comment]
Closing based on past agreement.
