### ISSUE TITLE
Add section 3.3.2 file path names

### ISSUE THREAD

**Issue by rosy1280** [OCFL/spec#413]
add section 3.3.2 to the spec.  
- [ ] discuss allowable characters in file names for the content path
- [ ] clearly state that file name restrictions identified in this section don't apply to the logical path.

for something similar take a look at [section 6.1.1.3 of the BagIt spec](https://tools.ietf.org/html/rfc8493#section-6.1.1.3)

**Comment by zimeon** [comment]
Also change 3.3.1 heading from `<h3>` to `<h2>` per respec norms (ref. #412)

**Comment by rosy1280** [comment]
contributes to closing #407
