### ISSUE TITLE
PairTree reference

### ISSUE THREAD

**Issue by pwinckles** [OCFL/spec#414]
I'm curious about the spec's reference(s) to PairTree. As far as I can tell, this is the most recent version of the PairTree spec: https://tools.ietf.org/html/draft-kunze-pairtree-01. It is a draft that hasn't been updated since 2009 and explicitly states the following at the top:

> Internet-Drafts are draft documents valid for a maximum of six months and may be updated, replaced, or obsoleted by other documents at any time.  It is inappropriate to use Internet-Drafts as reference material or to cite them other than as "work in progress."

I guess it doesn't matter as much for the implementation notes, but it seems out of place to cite it in the OCFL specification.

**Comment by ahankinson** [comment]
PairTree is implemented in a number of production systems and is widely known, so I think it makes sense to acknowledge it as a thing that is widely used, despite the notice. 

Unless there is a better reference for PairTree that we missed?

**Comment by pwinckles** [comment]
Not that I have been able to find. I don't know the history of it, so I've always found the PairTree situation odd. That is to say, odd that it would be widely used (is it?) but be unfinished and feature a number of undesirable performance characteristics.

**Comment by pwinckles** [comment]
Feel free to close this. I was mostly just drawing attention note at the top of the PairTree draft.

**Comment by zimeon** [comment]
Editors agree that we can close this
