### ISSUE TITLE
What limitations should there be on `contentDirectory`?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#415]
As [currently defined](https://ocfl.io/draft/spec/#inventory-structure) there are no restrictions on what `contentDirectory` might be. Perhaps:
  * It should be a single path element not a complex path (ie. no `/`) ?
  * It should have the same small number of limitations that are placed on logical paths (cf. #411) ?

Seems like an edge case so this could be left until after 1.0.

**Comment by pwinckles** [comment]
The spec does forbid `/` [here](https://ocfl.io/draft/spec/#content-directory).

> The contentDirectory value MUST NOT contain the forward slash (/) path separator.

**Comment by zimeon** [comment]
Thanks @pwinckles , that certainly answers my first bullet. I wonder whether there should be any other restrictions?

**Comment by pwinckles** [comment]
Yes, I agree. I am not allowing them in my client.
