### ISSUE TITLE
Are `.keep` files part of content or not?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#416]
From @julianmorley 's test fixture https://github.com/OCFL/fixtures/pull/5 it seems that we have different interpretations of the explanation of `.keep` files. The [current description]() is 

> Every file within a version's content directory MUST be referenced in the manifest section of the inventory. There MUST NOT be empty directories within a version's content directory. A directory that would otherwise be empty MAY be maintained by creating a file within it named according to local conventions, for example by making an empty `.keep` file.

My my reading of this, if one includes a `.keep` file or other local convention it MUST still be referenced in the manifest section of the inventory, ie. it is part of the OCFL object content. If we don't do that then we preclude other local conventions and/or make it impossible to include a file with content path `.keep` for any other purpose.

**Comment by ahankinson** [comment]
I believe the intention is that `.keep` files must still be referenced in the inventory.

**Comment by awoods** [comment]
I agree with @ahankinson . The statement:
> for example by making an empty .keep file.

..suggests that `.keep` is an example of a file that would ensure a directory is retained/valid... but also suggests `.keep` is not an OCFL convention/keyword.

:+1: to `.keep` being in the inventory.

**Comment by julianmorley** [comment]
Ah! It's not really a different interpretation. That .keep file in my fixture is an artifact of checking empty directories into Github. I fully agree that .keep files should be in the inventory.

**Comment by julianmorley** [comment]
Pasting from slack:
And as I thought, deleting the .keep removed the ‘content’ directory from GitHub. But for the fixture to be valid, the directory must be present, but empty.
So we may need to re-consider how to store fixtures here. We could do them as zips, have a fixture-creation script, or carve out an exception for a solitary .keep file in an otherwise empty ‘content’ directory.

**Comment by pwinckles** [comment]
Is this in regards to the `.keep` in object `of3` `v0002`? If so, why would the fixture be invalid if the content directory wasn't there? It's supposed to be a valid object version, yes? In which case, the content directory should NOT exist unless the version has binary changes.

> Version directories MUST contain a designated content sub-directory if the version contains files to be preserved, and SHOULD NOT contain this sub-directory otherwise.

**Comment by zimeon** [comment]
Yes indeed @pwinckles !

**Comment by awoods** [comment]
Should this issue be closed as "no change required"?

**Comment by zimeon** [comment]
Closing issue, no change required
