### ISSUE TITLE
Date format -- specification out of date

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#419]
Our currrent reference to ISO8601 is https://ocfl.io/draft/spec/#bib-ISO8601 --> http://www.iso.org/iso/catalogue_detail?csnumber=40874 which is withdrawn by ISO and replaced by https://www.iso.org/standard/70907.html (2019 version).

However, I really don't like using the ISO spec because it isn't openly available. It is also likely more complex than we need. I wonder whether we'd be better with with [W3C Datetime](https://www.w3.org/TR/NOTE-datetime) (although that isn't really a spec) or [RFC3339](https://tools.ietf.org/html/rfc3339)?

**Comment by awoods** [comment]
I agree that we certainly need to update the OCFL spec to reference an existing date/time specification... now that ISO8601:2004 has been withdrawn.

I also would prefer referencing an open specification.

https://tools.ietf.org/html/rfc3339 seems like a reasonable choice... as it is a profile of the ISO8601 specification that we currently use.
> This document defines a date and time format for use in Internet
> protocols that is a profile of the ISO 8601 standard for
> representation of dates and times using the Gregorian calendar.

**Comment by zimeon** [comment]
I think I'd be good with RFC3339, I wonder whether this is something we should bring up on a community call?

**Comment by awoods** [comment]
..or even raise it on the mailing list, since the next Community call is a month away.

**Comment by ahankinson** [comment]
I'm ok with RFC3339.

**Comment by zimeon** [comment]
Editors agree to use https://tools.ietf.org/html/rfc3339 , needs PR
