### ISSUE TITLE
Should we say that address SHOULD be a URI?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#422]
We [currently say](https://ocfl.io/draft/spec/#version-inventory):

> `user`
> The value of this key is a JSON object intended to identify the user or agent that created the current OCFL Version. The value of the `user` key MUST contain a user name key, `name` and SHOULD contain an address key, `address`. The `name` value is any readable name of the user, e.g., a proper name, user ID, agent ID. The `address` value is either a mailto URI [RFC6068] with the e-mail address of the `user` or a URL to a personal identifier, e.g., an ORCID iD.

which implies that the `address` should be a URI (mailto or personal id) but would perhaps be clearer as:

> ... The `address` value SHOULD be a URI: either a mailto URI [RFC6068] with the e-mail address of the `user` or a URL to a personal identifier, e.g., an ORCID iD.

**Comment by ahankinson** [comment]
I agree, it should be SHOULD.

**Comment by zimeon** [comment]
Editors' consensus is "SHOULD be a URI"
