### ISSUE TITLE
Move error codes from wiki into main git repo, with versioning

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#433]
Move content from the wiki https://github.com/OCFL/spec/wiki/OCFL-Validator-Codes into the main git repo, under the `draft` directory so that it will then be versioned as we version the spec

**Comment by awoods** [comment]
It is possible, if not likely, that we will want to version the spec and the validation codes separately.

**Comment by zimeon** [comment]
I suggest creating a new directory `validation` which can then have `ocfl-validation-codes.md` (with codes from current wiki page) and we will still rely on github to render rather than the ocfl.io site

**Comment by zimeon** [comment]
@awoods - how would you propose versioning separately?

**Comment by awoods** [comment]
Versioning separately could be achieved by having the codes in their own repo.

We may want to refine the codes without releasing a new version of the spec. Likewise, we may want to release a new version of the spec without releasing a new version of the codes... especially if the codes had not changed.

**Comment by zimeon** [comment]
I'd be loathe to create a separate repo just for this. I did consider the https://github.com/OCFL/validator repo but then you get confusing situations if that validator doesn't stay up to date.

Maybe the simplest solution would be to use the spec repo but have the `validation` directory at the top level? Not aligned with spec versions?

**Comment by zimeon** [comment]
Now live at https://github.com/OCFL/spec/blob/master/validation/validation-codes.md

**Comment by zimeon** [comment]
Have updated https://github.com/OCFL/spec/wiki/OCFL-Validator-Codes to remove content and instead link to the codes page
