### ISSUE TITLE
Can a logical path end with a slash?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#436]
Per https://ocfl.io/draft/spec/#version we rule a starting slash illegal, but not an ending one:

> Logical paths present the structure of an OCFL Object at a given version. This is given as an array of values, with the following restrictions to provide for path safety in the common case of the logical path value representing a file path. The logical path MUST be interpreted as a set of one or more path elements joined by a / path separator. Path elements MUST NOT be ., .., or empty (//). Additionally, a logical path MUST NOT begin with a leading /.

I think a trailing slash shouldn't be allowed either.

**Comment by rosy1280** [comment]
I'd like to hear @julianmorley 's thoughts on this

**Comment by rosy1280** [comment]
suggestion is to change the last sentence of the above to:

> Additionally, a logical path MUST NOT begin or end with a /.
