### ISSUE TITLE
Hex / base16 -- lowercase or mixed?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#437]
`md5` as defined by RFC1321 uses lowercase a...f in the hex so there is no uncertainty

`sha1` , `sha256`, `sha512`, and `blake2b-512` we define in terms of [RFC4648](https://tools.ietf.org/html/rfc4648) which says

> Essentially, Base 16 encoding is the standard **case-insensitive** hex encoding

and the examples in that spec use uppercase A...F. I see two options:

1) If we simply follow RFC4648 then all code needs to accept both upper and lowercase, and we have to think whether inconsistent case is acceptable within one object and describe that (also further complicating code). 

2) We could rewrite our section on digests to specify lowercase hex, along the lines of:

> `sha512` -- Default choice. Non-truncated form only. SHA-512 algorithm defined by \[FIPS-180-4] and MUST be encoded using hex (base16) encoding \[RFC4648] **using lowercase `a` through `f`**. For example, the `sha512` digest of a zero-length bitstream starts `cf83e1357eefb8bdf1542850d66d8007d620e405...` (128 hex digits long).

Discussion in https://github.com/OCFL/spec/issues/39 doesn't touch on case. Bagit allows either _"The hex-encoded checksum MAY use uppercase and/or lowercase letters"_ but digests do not serve the same role.

**Comment by zimeon** [comment]
I think we should define the digests to use lowercase hex. We avoid a while bunch of complexities around use of digests for reference by requiring lowercase. All the tools I use generate lowercase (`shasum` etc.) and that seems to be the norm now. It is trivial to convert any uppercase representation to lowercase when creating an inventory

**Comment by zimeon** [comment]
Was previously discussed in https://github.com/OCFL/spec/issues/149 that I missed -- this decided that we do not restrict case and added the following non-normative note:

> Implementers should be aware that base16 digests are case insensitive. Different tools will generate digests in uppercase or lowercase, and this may lead to case differences between references to a digest and the digest itself within the inventory. If string-based methods are used to work with digests and inventories (as is the case in most common JSON libraries) then extra care must be taken to ensure case-insensitive comparisons are being made.

**Comment by zimeon** [comment]
Closing this issue as sense on editors' call is not to reopen the issue

**Comment by neilsjefferies** [comment]
As per Community Call 13/5 - agreed each digest should occur only once in the manifest regardless of case.
