### ISSUE TITLE
Rewrite description of sidecar file to remove uncheckable MUST

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#448]
Per #444 we end up with 3 RFC2119 MUST for [describing inventory sidecar files](https://ocfl.io/draft/spec/#inventory-digest). I think we need only 2 MUST and propose changing the text to something like:

> Every occurrence of an inventory file [E058]MUST have an accompanying sidecar file named inventory.json.ALGORITHM stating its digest, where ALGORITHM is the chosen digest algorithm for the object. The ALGORITHM [E059]MUST match the value given for the digestAlgorithm key in the inventory. An example might be inventory.json.sha512.

which has the effect of removing E092

**Comment by julianmorley** [comment]
There's also https://ocfl.io/draft/spec/#E065 a bit further down;
```
Every inventory file must have a corresponding Inventory Digest.
```
Which is also redundant.

**Comment by zimeon** [comment]
New issue for E065?

**Comment by julianmorley** [comment]
Done!
https://github.com/OCFL/spec/issues/449

**Comment by zimeon** [comment]
Agreement in editors' call to make change as above https://github.com/OCFL/spec/issues/448#issue-596643177
