### ISSUE TITLE
Remove or edit redundant MUST statement

### ISSUE THREAD

**Issue by julianmorley** [OCFL/spec#449]
https://ocfl.io/draft/spec/#E065 is currently:
```
Every inventory file must have a corresponding Inventory Digest.
```
This seems to be covered by E058:
```
Every occurrence of an inventory file must have an accompanying sidecar file stating its digest.
```
As it stands a validation for inventory sidecars would raise both E058 and E065 if the sidecar file was not found. I think the offending E065 statement could just be removed entirely, or perhaps re-worded to refer back to the earlier statements.

**Comment by zimeon** [comment]
While I think we could just delete the sentence with E065, technically it is redundant, I think we miss an opportunity to remind readers about the digest. How about changing to a reference only: 

> See also requirements for the corresponding [Inventory Digest](https://ocfl.io/draft/spec/#inventory-digest).

**Comment by zimeon** [comment]
Agreement in editors' call to make change as above
