### ISSUE TITLE
Digest vs checksum vs hash

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#46]
In the current draft we take about digests, checksums and hashes... I think it is unhelpful to use three terms when we mean the same thing. I propose that we always say "digest" for the output and that we never say "checksum" (unless we somewhere wanted to say "digest, sometimes called a checksum"). We might also use "hash" to talk about the algorithms and the calculation but I would again stick to "digest" for the output

**Comment by ahankinson** [comment]
Use `digest` for the language in the spec. Use language that avoids 'hash' and 'checksum', e.g, not "hash algorithm" but "algorithm to compute the digest".
