### ISSUE TITLE
Logical paths MUST not have element . .. or //, but what about content paths?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#462]
It seems we specify a number of restrictions on logical paths so that an object can be unpacked on a unix-like filesystem (https://ocfl.io/draft/spec/#version):

> The logical path must be interpreted as a set of one or more path elements joined by a / path separator. Path elements must not be ., .., or empty (//). Additionally, a logical path MUST NOT begin or end with a forward slash (/).

but we don't actually say anything comparable about content paths (https://ocfl.io/draft/spec/#manifest). I think currently the following is not disallowed:

```
"manifest": {
    "7dcc35...c31": [ "v1/content/foo/down/../bar.xml" ],
    "cf83e1...a3e": [ "v1/content/////empty.txt" ],
    "ffccf6...62e": [ "v1/content/./././././image.tiff" ]
  }
```

**Comment by neilsjefferies** [comment]
Likewise duplication and files can't also be folders.

**Comment by neilsjefferies** [comment]
As per Community Call 13/5 - same restrictions as for logical paths (and a corresponding set of new error codes)

**Comment by zimeon** [comment]
2020-05-19 Editors agree that we should address this as described
