### ISSUE TITLE
Invalid link in section 4.1

### ISSUE THREAD

**Issue by bcail** [OCFL/spec#466]
There seems to be an invalid link in section 4.1 "Root Structure". The link to "storage root extensions" in the second paragraph should point to https://ocfl.io/draft/spec/#storage-root-extensions, instead of https://ocfl.io/draft/spec/#root-extensions.

**Comment by awoods** [comment]
@bcail : Would you be able to contribute a pull-request?

**Comment by zimeon** [comment]
Closed by #367
