### ISSUE TITLE
Clarify meaning of "registered extension name"

### ISSUE THREAD

**Issue by awoods** [OCFL/spec#486]
Follow-on issue related to: https://github.com/OCFL/spec/issues/477

..see: https://github.com/OCFL/spec/pull/483#pullrequestreview-434083410

**Comment by zimeon** [comment]
https://github.com/OCFL/extensions/pull/13/files attempts to do this with the following text:

> The *Registered Name* of an extension is the name of the extension file in the `docs` directory, excluding the `.md` extension.

If we want to do more _in the specification_ then I think a [terminology entry](https://ocfl.io/draft/spec/#terminology) for [registered extension name](https://ocfl.io/draft/spec/#dfn-registered-extension-name) would be the best approach, and it could then be linked from that term in both https://ocfl.io/draft/spec/#object-extensions and from https://ocfl.io/draft/spec/#root-structure

**Comment by rosy1280** [comment]
I agree with @zimeon 's assessment and thumbs upped it to show agreement.  Would love to see if others have thoughts.  

cc'ing folks so we can get movement: @awoods @neilsjefferies @ahankinson @julianmorley

**Comment by ahankinson** [comment]
I think we should have an entry in the terminology section, and will volunteer to write the PR if agreed.

**Comment by ahankinson** [comment]
oops... @awoods beat me to it.
