### ISSUE TITLE
Section 2: Populate Terms

### ISSUE THREAD

**Issue by awoods** [OCFL/spec#49]
This task is to add the terms (if not their definitions) to section 2: Terminology.

**Comment by rosy1280** [comment]
- OCFL Object
- OCFL Object Root
- OCFL Storage Root
- Inventory File
- Inventory Digest
- Version
- Moab
-BagIt

**Comment by rosy1280** [comment]
Definitions should be formatted like so:

```
<dl>
        <dt><dfn>Term One</dfn>:</dt>
        <dd>Definition goes here.</dd>
        <dt><dfn>Term Two</dfn>:</dt>
        <dd>Definition goes here.</dd>
</dl>
```
