### ISSUE TITLE
Clarify that the digests are for de-duping 

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#5]
From [2018-03-28 meeting notes](https://docs.google.com/document/d/1UOEdzNqh59SSstWw78HblLQPSfqB_A55ci1tVeZkq1Y/edit#) there was a "decision" about the need to:

> Be super clear that checksums are for de-duping, not for fixity checking (e.g. guarding against malicious acts)

**Comment by zimeon** [comment]
I think one way to help with this might be to refer to them as *digests* or *hashes* rather than *checksums*. (I tend to go with *digests*.)

**Comment by ahankinson** [comment]
Technically, digests are used for referencing within the inventory. De-duping happens as a side-effect. The hashes were used to distinguish between two different files with the same name (otherwise we could just use path names as identifiers and skip _digesting_ (?) altogether). It just happens to also catch the case where two different files could have the same content.

**Comment by awoods** [comment]
@ahankinson : are you suggesting that the "clarification" of digests be extended to mention "referencing within the inventory" as well as "de-duping"?

**Comment by ahankinson** [comment]
A digest in the inventory file serves the _primary_ purpose of making a file addressable by its checksum value. The manifest section of the inventory contains a key-value object, mapping a digest (key) to a file path (value). In the versions metadata, files that are constituents members of that version are referenced by *digest*.

Thus it has the function of both de-duplication (you cannot have a hash with the same key twice) and addressing (the digest is related to the filepath within the inventory, and it is used to reference the parts of the version metadata).

**Comment by awoods** [comment]
In terms of resolving this issue, maybe a PR with text into https://ocfl.io/#digest-algorithm-choice would be a place to start.

**Comment by ahankinson** [comment]
Editorial Meeting Decision: 2018-08-15: Agreed in #46 that we would use "Digest" consistently, and that we will talk about de-duping and addressing functions separately.
