### ISSUE TITLE
Relationship to BagIt bags

### ISSUE THREAD

**Issue by awoods** [OCFL/spec#50]
The overlap and similarity between OCFL and BagIt has been noted several times.
https://tools.ietf.org/html/draft-kunze-bagit-08

BagIt bags are fundamentally composed of a directory that contains:
- bagit version file
- manifest of data files
- "data" directory of arbitrary content files

The primary difference with OCFL is the administrative metadata detailing changes associated with a given version.

Would it make sense to adapt the OCFL definition of a "version" directory to look more like a BagIt bag with the addition of `inventory.jsonld`?

**Comment by rosy1280** [comment]
No longer the case.  Closing.
