### ISSUE TITLE
The referenced JSON RFC is obsolete

### ISSUE THREAD

**Issue by pwinckles** [OCFL/spec#507]
[The spec](https://ocfl.io/1.0/spec/#bib-json) references [rfc4627](https://tools.ietf.org/html/rfc4627) which is obsolete. The current JSON spec is [rfc8259](https://tools.ietf.org/html/rfc8259).

**Comment by zimeon** [comment]
Well spotted @pwinckles, not even one revision out of date but 2 or 3!
