### ISSUE TITLE
guarding against inconsistent version histories

### ISSUE THREAD

**Issue by pwinckles** [OCFL/spec#517]
The procedure described in the implementation notes to update objects does not provide protection against concurrent modifications creating an object with an inconsistent version state.

Let's imagine that we have an object that currently has 3 versions. We start a process to update the object and create a new version as described in the notes. At the same time, a different process "rollsback" the latest version of the same object, removing `v3` and installing the `v2` inventory in the root, and then immediately updates the object to create a new `v3`. Finally, the original process finishes, creating a `v4` that is inconsistent with the current object state.

This can be guarded against by recording the previous inventory digest when a new inventory is created, and then comparing this digest to the root inventory digest _after_ moving the new version into the object root but _before_ the new version's inventory is installed in the root. If they don't match, the new version directory must be deleted.

This may be an uncommon edge-case (not to mention the notes never discuss the possibility of removing versions), but I thought I'd share it in case you wanted it in the implementation notes.

**Comment by neilsjefferies** [comment]
Rolling back versions is not a defined operation on an OCFL object since it breaks immutability. You should do a purge/object recreate.

**Comment by pwinckles** [comment]
It is true that it breaks object immutable, but at least it does not mutate anything within a version.

I view it as a necessary operation in order to support some semblance of a multi-object transaction. Let's use Fedora as a concrete example.

In Fedora you could create a transaction, update multiple objects, and then commit the transaction. When the transaction is committed, Fedora must persist all of the changes to OCFL objects and make a number of DB updates. If any of these operations fail, the state should be rolled back to the state before the transaction was started. Implementing this behavior by purging and recreating entire OCFL objects is unreasonable.

**Comment by neilsjefferies** [comment]
That's why there are transaction ID's. Either the rollback shouldn't start since there is a transaction in progress on the object already, or the transaction that requires the rollback is still holding a transaction ID so a new object update won't start.

**Comment by pwinckles** [comment]
I don't see how transaction ids are relevant. It's impossible to atomically update multiple OCFL objects. If you want to ensure that either an entire set of objects is updated or none of them are, the only options seem to be a) "rolling back" unwanted versions or b) purging and recreating objects without the unwanted versions. To me, the later seems too heavy handed to be practical.

**Comment by neilsjefferies** [comment]
In a way that is true - it is a physical property of storage. That's why databases have transaction logs, complex locking schemes, and replay mechanisms and a whole load of other stuff and they still get corrupted. It is also why high performance databases are eventual consistency with a degree of acceptable loss.  However, if you don't release ID's until all the objects in a transaction have been safely updated, the cleanup is relatively quick and the need filesystem locking at the object level is minimised.

**Comment by neilsjefferies** [comment]
This has to be handled in application logic. This is outside the scope of the OCFL specification. Has been superseded by work by @pwinckles on Fedora etc. that handles this.
