### ISSUE TITLE
Should we use UK or US spelling?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#52]
Brought up in discussion of #44... we need to pick one and be consistent

**Comment by zimeon** [comment]
I'm fine with either option, we just need a decision. In some ways it would seem most consistent to use English spelling for a spec named "Oxford (in England) Common File Layout".

**Comment by awoods** [comment]
Agreed. "Oxford" would suggest UK spelling.

**Comment by zimeon** [comment]
W3C uses US (or did in 2001): https://www.w3.org/2001/06/manual/#Spelling

**Comment by ahankinson** [comment]
On editors call 2018-08-15, decided to use US English.

**Comment by ahankinson** [comment]
https://www.w3.org/2001/06/manual/#Spelling
