### ISSUE TITLE
Missing requirement that non-zero-padded version numbers are prefixed with 'v'

### ISSUE THREAD

**Issue by pwinckles** [OCFL/spec#532]
Spec:

> The sequence of version numbers is the sequence of positive, base-ten integers: 1, 2, 3, etc., and the version directory name is constructed by adding the prefix v.

Validation codes:

- `E009`: ‘The version number sequence MUST start at 1 and must be continuous without missing integers.’
- `E010`: ‘The version number sequence must start at 1 and MUST be continuous without missing integers.’
- `E011`: ‘If zero-padded version directory numbers are used then they must start with the prefix v and then a zero.’

There is no code requiring non-zero-padded version numbers to begin with `v`. I assume this is because the spec is missing a MUST in the quoted sentence.

**Comment by zimeon** [comment]
I see my validator gives an `E009` if I put a version `1` (as opposed to `v1`) which isn't covered by the description.

I agree that it would be helpful to have a MUST that all version directory names start with `v`, and that this is separate from the current `E009`, `E010`, `E011` (which should perhaps be just about zero padding)

**Comment by zimeon** [comment]
I propose rewriting the first paragraph of https://ocfl.io/1.0/spec/#version-directories in v1.1 to include an additional MUST, along the lines of @pwinckles' suggest. Change from:

> OCFL Object content MUST be stored as a sequence of one or more versions. Each object version is stored in a version directory under the object root. The sequence of version numbers is the sequence of positive, base-ten integers: 1, 2, 3, etc., and the version directory name is constructed by adding the prefix `v`. The version number sequence MUST start at 1 and MUST be continuous without missing integers.

to 

> OCFL Object content MUST be stored as a sequence of one or more versions. Each object version is stored in a version directory under the object root. Version directory names MUST be constructed by prepending `v` to the version number, taken from the sequence of positive, base-ten integers: 1, 2, 3, etc.. The version number sequence MUST start at 1 and MUST be continuous without missing integers.

**Comment by awoods** [comment]
Just word-smithing here:
> OCFL Object content MUST be stored as a sequence of one or more versions. Each object version is stored in a version directory under the object root. Version directory names MUST be constructed by prepending v to the version number. The version number MUST be taken from the sequence of positive, base-ten integers: 1, 2, 3, etc.. The version number sequence MUST start at 1 and MUST be continuous without missing integers.
