### ISSUE TITLE
Manifest is missing MUSTS

### ISSUE THREAD

**Issue by pwinckles** [OCFL/spec#533]
The manifest section does not have the same level of thoroughness when it comes to MUSTS as the versions section does. For example:

> The value of the manifest key is a JSON object, with keys corresponding to the digests of every content file in all versions of the OCFL Object.

vs

> An OCFL Object Inventory MUST include a block for storing versions. This block MUST have the key of versions within the inventory, and it MUST be a JSON object.

The result is that the validation codes are not as specific for `manifest` and rely more on inferences from other codes. In this example, if `manifest` is not a JSON object I think `E033` makes the most sense. Whereas, if `versions` is not a JSON object the more specific `E044` could be used.

**Comment by zimeon** [comment]
So far, I have used `E041` for either missing `manifest` key or it not being a JSON object, based on:

> In addition to these keys, there <span id="E041">MUST</span> be two other blocks present, <code>manifest</code> and <code>versions</code>, which are discussed in the next two sections.

if the "is a" became a "MUST" in:

> The value of the manifest key is a JSON object, with keys corresponding to the digests of every content file in all versions of the OCFL Object.

then that would clearly take over for the "not an object" case.

Seems that there is no lack of clarity for what is correct here, just uncertainty over the best way to handle validation. I think this makes it a 2.0 (or 1.1) issue.

**Comment by awoods** [comment]
This specific example may be resolved by: https://github.com/OCFL/spec/issues/537#issuecomment-913782831

**Comment by zimeon** [comment]
Addressed by #561
