### ISSUE TITLE
must a manifest entry be referenced in at least one version's state

### ISSUE THREAD

**Issue by pwinckles** [OCFL/spec#537]
Fixture [E050_file_in_manifest_not_used](https://github.com/OCFL/fixtures/tree/main/1.0/bad-objects/E050_file_in_manifest_not_used), is a test for a manifest entry that is not referenced in any version state. It specifies the error should be `E050`:

> The keys of [the “state” JSON object] are digest values, each of which must correspond to an entry in the manifest of the inventory.

That text states that every logical path MUST have a corresponding manifest entry. It does not state that ever manifest entry MUST have at least one corresponding logical path. The nearest I can find to such a requirement in the spec is:

> The value of the manifest key is a JSON object, with keys corresponding to the digests of every content file in all versions of the OCFL Object.

But, that line, besides not having an associated validation code, is ambiguous. If "versions" are version objects in the inventory, then that could be read as requiring that every manifest entry be references in at least one version's state. But, if "versions" are version directories on disk, then it doesn't seem to be a requirement at all.

**Comment by awoods** [comment]
Suggested resolution:
1. Update text of first sentence of [3.5.2 Manifest](https://ocfl.io/draft/spec/#manifest) to:
   > The value of the <code>manifest</code> key is a JSON object, all keys of which <span id="XXXX">MUST</span> correspond to digest value keys found in one or more state JSON objects of the current and/or previous <a>version</a> blocks of the <a>OCFL Object</a>.
2. Update [E050_file_in_manifest_not_used](https://github.com/OCFL/fixtures/tree/main/1.0/bad-objects/E050_file_in_manifest_not_used) to reference the newly created requirement code from above.
3. Create a new test that checks the scenario of [E050](https://ocfl.io/draft/spec/#E050) wherein a file in the version's state object is not found in the object's manifest.

**Comment by zimeon** [comment]
Proposing a PR with minor wording change from the above:
> The value of the manifest key must be a JSON object, and each key must correspond to a digest value key found in one or more state JSON objects of the current and/or previous version blocks of the OCFL Object.
