### ISSUE TITLE
validation issues in spec examples

### ISSUE THREAD

**Issue by pwinckles** [OCFL/spec#539]
I noticed a few problems with the spec examples:

1. All of the examples include an `address` that is not a URI
2. [This example](https://ocfl.io/1.0/spec/#example-object-diff-paths) is missing a `user`
3. The Moab example is invalid because the versions in its inventory are not zero-padded; while the version directories on disk are

**Comment by pwinckles** [comment]
Additionally, I just glanced at the examples in the implementation notes. The `addresses` are correct there, but all of the `created` timestamps are missing their offset.

**Comment by zimeon** [comment]
Thanks @pwinckles , sigh re spec errors:

1. Yes, the `address` entries should all have a `mailto:` prefix
2. I agree that https://ocfl.io/1.0/spec/#example-object-diff-paths would give a warning, probably best that spec examples don't give warnings unless there is a good reason, and maybe then the expected warning and reason should be made explicit
3. Yikes, yes. Per https://ocfl.io/1.0/spec/#versions the Moab example should generate https://ocfl.io/1.0/spec/#E046 _"The keys of [the `versions`] object MUST correspond to the names of the version directories used."_

**Comment by rosy1280** [comment]
Moab objects still need to be fixed.
