### ISSUE TITLE
Action: Fix spelling in spec to be US Spelling

### ISSUE THREAD

**Issue by ahankinson** [OCFL/spec#54]
Follows on decision made in #52

**Comment by zimeon** [comment]
Stealing this from @ahankinson as it seems a good task to pass the time on a flight. Have also started a page https://github.com/OCFL/spec/wiki/OCFL-Specification-Style-Guide

**Comment by zimeon** [comment]
Also changing one case of "implementors" to be "implementers" (the more common spelling) so that we are consistent
