### ISSUE TITLE
Clarify that `id` must be consistent across all versions

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#542]
@awoods comment in https://github.com/OCFL/fixtures/pull/87:
> Should we add text around https://ocfl.io/draft/spec/#E037 along the lines of: _This must be set in the first version of the object, must be unique in the local context, and must not change between versions of the same object._?

**Comment by zimeon** [comment]
I like the idea of clarifying the text that the `id` must be consistent across all versions. I don't think we should define it in terms of the first version however, because the `v1` inventory may or may not stored and, for the case that all inventories are stored, I think typical validation strategy will be to start with the root/latest inventory and work backwards to check consistency

**Comment by awoods** [comment]
Updated wording (around https://ocfl.io/draft/spec/#E037) focused on consistency of object `id` across all "inventory.json" files at the object root and within version directories:
> This must be unique in the local context and must not change between versions of the same object.
