### ISSUE TITLE
Do 1.1 compliant objects declare themselves at 1.0 or 1.1?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#543]
Discussed in https://github.com/OCFL/spec/wiki/2021.05.12-Community-Meeting, will the [conformance declaration](https://ocfl.io/1.0/spec/#object-conformance-declaration) for a 1.1 compliant object say 1.0 or 1.1?

In discussion we confirmed that versions are expected to be immutable so prior versions and their inventories (which include the [versioned `type` declaration](https://ocfl.io/1.0/spec/#inventory-structure)) may accord with different versions.

**Comment by rosy1280** [comment]
just the most recent version should be 1.1

**Comment by zimeon** [comment]
Agreed that we will declare 1.1 as distinct from 1.0. This is already written into the spec. per https://github.com/OCFL/spec/pull/552

cf. also agreed (and added into spec) the idea of monotonic spec version numbers in the content version sequence https://github.com/OCFL/spec/issues/544

**Comment by awoods** [comment]
Given the updates from https://github.com/OCFL/spec/pull/552 and https://github.com/OCFL/spec/pull/550, is there anything else to do with this issue? It seems agreed upon and resolved.
