### ISSUE TITLE
Should we version validation_codes.md?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#553]
I think when we created https://github.com/OCFL/spec/blob/main/validation/validation-codes.md we imagined consistency of error and warning codes between versions. I think we should certainly maintain this but I think we should version the validation codes file (perhaps move it into the spec directory) because:
  1. How do we add a new error code in draft or for a new version without creating confusion? E.g. https://github.com/OCFL/spec/pull/550
  2. Even if we maintain codes, we may change descriptions from version to version

**Comment by awoods** [comment]
Yes, moving the [validation/](https://github.com/OCFL/spec/tree/main/validation) directory into [draft/](https://github.com/OCFL/spec/tree/main/draft) as siblings of 'spec/' and 'implementation-notes/' would be helpful.

**Comment by zimeon** [comment]
Would it be better/simpler to have `validation_codes.md` in the `spec` directory instead?

**Comment by awoods** [comment]
As long as the `validation_codes.md` lives in "draft/", and subsequently "1.1/", "2.0/", etc... I am fine with locating it within "draft/spec/" or "draft/validation/".
