### ISSUE TITLE
Change specification source from Respec to Markdown

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#554]
I think we should change the OCFL specifications from Respec to Markdown:
  * In Markdown we'd have better control of formatting and not end up fighting Respec (see [issues and PRs](https://github.com/OCFL/spec/issues?q=respec+))
  * We would immediately solve #505 with the ability to add `ocfl.md` and/or `ocfl.html` to the Storage Root
  * Compilation with Jekyll is required (a downside) but then we would have a static HTML file that doesn't rely on JavaScript lookups for rendering (a big upside, meaning our spec is preservable)
  * We don't need the "looks like a W3C spec" fake authenticity

**Comment by zimeon** [comment]
Example of spec in Markdown: https://iiif.io/api/presentation/3.0/

**Comment by awoods** [comment]
On https://github.com/OCFL/spec/wiki/2021.06.15-Editors-Meeting, we decided that transitioning to Markdown would be a constructive move forward.

**Comment by pwinckles** [comment]
If Markdown's limited features is an issue, [asciidoc](https://asciidoc.org/) is an alternative.

https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/

**Comment by zimeon** [comment]
Work in progress, current versions from automated conversion at:
* https://zimeon.github.io/ocfl-spec2md/spec
* https://zimeon.github.io/ocfl-spec2md/impl
* Work to do: https://github.com/zimeon/ocfl-spec2md/issues

**Comment by zimeon** [comment]
Decision at https://github.com/OCFL/spec/wiki/2022.05.19-Editors-Meeting is that we will not convert existing versions (notably 1.0). Future version, the draft spec, 1.1 etc., will be in Markdown

**Comment by zimeon** [comment]
Things to consider after we have the first markdown version merged:
* We should decide on styling of literals, I think it is good they are no longer red like the RFC2119 words, but not sure the current grey background is good
* We can consider syntax highlighting options for the code segments
