### ISSUE TITLE
Denoting non-normative text

### ISSUE THREAD

**Issue by awoods** [OCFL/spec#57]
Suggestion: 
1. Non-normative sections should be denoted with the use of:
```
<section id="whatever" class="informative">
```
2. Non-normative blocks within a section should be denoted with the use of:
```
<blockquote class="informative">
  <p>
    Non-normative note:
    ...text...
  </p>
<blockquote/> 
``

**Comment by zimeon** [comment]
In the Fedora spec we add the text "Non-normative note: " in each block, e.g. https://github.com/fcrepo/fcrepo-specification/blob/master/index.html#L214

**Comment by ahankinson** [comment]
Sure; I guess I'm just saying that respec only adds the 'non-normative' text when it's on `<section>`; otherwise it ignores that class. So we can get the same effect if we just use `<blockquote>` with no class and add the text in manually.
