### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by vsoch** [OCFL/spec#59]
hey @zimeon, @neilsjefferies, @awoods, @ahankinson, @rosy1280. I'm in research
computing at Stanford, and was having a discussion about how the problem of
reproducibility (or encapsulation of a workflow) might be differently (maybe better?)
addressed if we spent more time looking at the organization of the data / inputs,
as opposed to "which workflow manager to use." Software (containers) could be designed
around these rules, and instead of a complicated set of inputs and outputs, the
software would understand a dataset format. Datasets would be able to find
software that work with them, and vice versa. You could also do things like move more
easily between object storage, local filesystem, and traditional databases, because
given that you can predict how files are organized, you can programatically change them
and (still) have programmatic accessibility. As an example, the [Brain Imaging Data
Structure](https://en.wikipedia.org/wiki/Brain_Imaging_Data_Structure) (BIDS) has done great things for neuroimaging informatics, for exactly these reasons.

Anyway, I was having this discussion with my colleague @akkornel, and he is aptly
skilled in poking around for more information, and he found [https://ocfl.io/](https://ocfl.io/)! And I'm super happy that you exist!! This is so important. I want to ask (see title of this post) how can I help?

**Comment by ahankinson** [comment]
Hey @vsoch have you reached out to @julianmorley ? He’s super close to you :)

**Comment by vsoch** [comment]
Haha probably not? I work remotely from the East Coast so it might be a stretch :)

**Comment by awoods** [comment]
@vsoch : We will be making a concerted push next week to flush out more of the OCFL specification. In terms of how you can help, it would be valuable to get your input on that (more detailed) version of the document. 
https://ocfl.io/
