### ISSUE TITLE
Clarify that all information about object must be serialized in the object

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#6]
From [2018-03-28 meeting notes](https://docs.google.com/document/d/1UOEdzNqh59SSstWw78HblLQPSfqB_A55ci1tVeZkq1Y/edit#) there was a "decision" about the need to:

> Clarification:  All the information about the object should be serialized in the object (metadata as well as …) as a consequence of the rebuildability requirement

**Comment by awoods** [comment]
I certainly agree from the rebuildability perspective. It would be helpful to clarify what we mean by "All the information".

**Comment by zimeon** [comment]
Addressed by #75, closing
