### ISSUE TITLE
start of Feedback on Draft

### ISSUE THREAD

**Issue by vsoch** [OCFL/spec#60]
The reason this is so important is because containers either have a single entrypoint, or a programatically predictable (internally modular) set of entrypoints (e.g., see [https://sci-f.github.io](https://sci-f.github.io).
https://github.com/OCFL/spec/blob/9a2fd7b583741474812d92bcc6f5fba23713e1e2/index.html#L113-L120

Right now the Scientific Filesystem (scif above) has internal modularity for the software inside, and it has a spot for data, but not any specification to how it's organized. This would be a really strong use case for how the standard can work with containers.

## Best Practices

We might want to be conservative about saying "best practices." It **is** developing a standard so it's (by definition) something like that, but many will hear "best practices" and immediately have reason that it's not the absolute best.

https://github.com/OCFL/spec/blob/9a2fd7b583741474812d92bcc6f5fba23713e1e2/index.html#L116

What if instead we say "reproducible practices" or "standardized practice" and use a more descriptive word than "best" ?

## Two Specifications

This part

https://github.com/OCFL/spec/blob/9a2fd7b583741474812d92bcc6f5fba23713e1e2/index.html#L122-L125

I think there are two (very big and different) things here that would need to eventually work together. The first part to tackle I think is just the first point, and doing so to do it with the second in mind. The second is the language to interact with it. This again smells a lot like scif --> https://sci-f.github.io/spec-v1 in that the main difference being that scif has user interface commands that "feel" a lot like how you would interact with a container (e.g. "run" "exec" "shell") but notably, it doesn't have to be installed in a container. 

I think it would be stronger to package these two things somewhat separately, because even if you branded them under the same label, I can see use cases where someone might want one or the other (but not both).

https://github.com/OCFL/spec/blob/9a2fd7b583741474812d92bcc6f5fba23713e1e2/index.html#L129-L131

digital repositories such as? A file system in an old library is different from object storage, which is different from a flat database, which is different from a relational.

https://github.com/OCFL/spec/blob/9a2fd7b583741474812d92bcc6f5fba23713e1e2/index.html#L131-L135

This is a really important point - I don't think that institutions even know what these metadata are, at least the ones that have awareness of it are farther along. This is probably more challenging than making the standard itself - going across software / archives in general for data or other and deciding what are the "important metadata." There needs to be a whole workflow to create groups, assign responsibilities, and go through change cycles just for doing that. This is another reason I would set aside the set of functions for now - the needs and functions for interacting with the data structure probably are going to vary based on the domain, and also might be better carried out by third party software that writes tools understanding the datastructure.

https://github.com/OCFL/spec/blob/9a2fd7b583741474812d92bcc6f5fba23713e1e2/index.html#L159-L162

What do these permissions look like? POSIX? Something else? How does this vary based on traditional NFS vs an object store or a signed container?

https://github.com/OCFL/spec/blob/9a2fd7b583741474812d92bcc6f5fba23713e1e2/index.html#L171-L176

So this is scoped to a filesystem then? A filesystem in a container?

Another gut reaction is that this sounds a lot like what people would describe as a "data container" but just with a required organization inside. Again a little bit like scif, since it has the /scif root and a predictable structure for the contents within :)

Are there any example use cases? That might be useful.

So I would say this is really great so far! Maybe for this first draft focus on just the organization, and a plan for how the community works around it? Then either solutions will start to emerge (or a need for a general set of functions) for interacting with the data structures.

**Comment by rosy1280** [comment]
@vsoch the specification has changed significantly since you first reviewed this.  Perhaps some of the questions you answered are more readily understood by reading the specification.  I'm going to close this right now, but if you still have questions, please let me know.

**Comment by vsoch** [comment]
It would be nice if next time there was feedback on this much earlier than "there has been so much change it's irrelevant, closing issue." :( But thanks anyway for the update.

**Comment by rosy1280** [comment]
@vsoch apologies for not providing a more helpful comment. This ticket was submitted shortly before the OCFL editors had their first face to face meeting. The intent of that meeting was to flesh out the draft to get us closer to a version 1 of the specification. In our last push to get to an alpha release, I chose to take on this ticket.

In trying to respond, I found myself rewriting much of what the specification and it's implementation notes explain. Ultimately it made sense to me to refer you back to the spec rather than rewriting it here.

I do hope that you have a chance to review the spec because I think much of what you asked in this ticket is answered there. If you don't believe that is the case, then please let us know so that we can further clarify for our beta release.
