### ISSUE TITLE
NAMASTE reference points to non-public location

### ISSUE THREAD

**Issue by scossu** [OCFL/spec#623]
The link at https://ocfl.io/1.1/spec/#ref-namaste points to https://confluence.ucop.edu/download/attachments/14254149/NamasteSpec.pdf which requires authentication.

**Comment by zimeon** [comment]
Thanks @scossu ! That didn't use to be the case. I see only a 2022-09-30 copy in the Wayback Machine that is the current 302 to login (https://web.archive.org/web/20220915000000*/https://confluence.ucop.edu/download/attachments/14254149/NamasteSpec.pdf). I wonder what the proper link should be? Any advice @jkunze?

**Comment by jkunze** [comment]
Hmm. I don't know why CDL is hosting that spec behind a password challenge. Here's a better link at IA: https://ia801702.us.archive.org/2/items/ark_13030_c7g44hq41/NamasteSpec.pdf

**Comment by zimeon** [comment]
Thank you @jkunze . Is the URI without the preceding `ia801702.us.` canonical: https://archive.org/2/items/ark_13030_c7g44hq41/NamasteSpec.pdf ?

**Comment by zimeon** [comment]
or maybe https://archive.org/download/ark_13030_c7g44hq41/NamasteSpec.pdf from looking at https://archive.org/download/ark_13030_c7g44hq41

**Comment by jkunze** [comment]
@zimeon Sorry, that link I suggested was a hasty paste from my phone. A better link is https://n2t.net/ark:/13030/c7g44hq41
