### ISSUE TITLE
Pairtree link in v1.1 of spec goes to a confluence page that requires login

### ISSUE THREAD

**Issue by ptsefton** [OCFL/spec#627]
https://confluence.ucop.edu/display/Curation/PairTree

**Comment by rosy1280** [comment]
a potential replacement link is https://datatracker.ietf.org/doc/html/draft-kunze-pairtree-01 but that is an expired and archived draft so.....

**Comment by neilsjefferies** [comment]
Internet Archive link is rather unsatisfactory. Pairtree is not vital to the spec but we could include the spec as a storage layout extension if it has a tendency to go walkies.

**Comment by rosy1280** [comment]
We will link to the datatracker url indicated above.  if for some reason that goes away, OCFL will add this specification to its documentation using the [wayback machine's most recent version of the page](https://web.archive.org/web/*/https://datatracker.ietf.org/doc/html/draft-kunze-pairtree-01).
