### ISSUE TITLE
update NAMASTE link in Implementation Notes

### ISSUE THREAD

**Issue by srerickson** [OCFL/spec#630]
The NAMASTE reference URL was [fixed in the spec](https://github.com/OCFL/spec/issues/623), but not in the [implementation notes](https://ocfl.io/1.1/implementation-notes/#informative-references).

**Comment by hixhix** [comment]
Please update also the URL at https://ocfl.io/1.1/spec/#ref-namaste

**Comment by srerickson** [comment]
My mistake. The links were fixed in `draft` and I'm guessing the published spec can't be changed. It would be nice if the updates in draft were more visible but that would be another issue.
