### ISSUE TITLE
changes to Implementations wiki

### ISSUE THREAD

**Issue by srerickson** [OCFL/spec#636]
I'd like to update the entries on the [implementations wiki](https://github.com/OCFL/spec/wiki/Implementations) concerning my projects: the library is now called `ocfl-go` and the `gocfl` cli has been removed from that repo. (I'll be sharing a new cli project soon, I hope!)

My suggestion:

```md 
- [ocfl-go](https://github.com/srerickson/ocfl-go) (Go, Seth Erickson, University of California, Santa Barbara)
    - [ocfl-index](https://github.com/srerickson/ocfl-index) storage root indexer based on ocfl-go.
```

Thank you!

**Comment by awoods** [comment]
@srerickson : Thanks for helping keep the list of resources current. You should have 'edit' permissions on the wiki. If you don't, please let me know.

Please feel free to make the changes directly.

**Comment by srerickson** [comment]
Thanks. I wasn't sure because there's a line at the top about opening an issue.
