### ISSUE TITLE
Broken links in OCFL 1.1 specs

### ISSUE THREAD

**Issue by max-moser** [OCFL/spec#645]
It seems like two of the links in the "6. References" section at the [OCFL 1.1 spec](https://ocfl.io/1.1/spec/) are broken:
* [PairTree](https://ucopedu.atlassian.net/wiki/spaces/Curation/overview) shows only a warning about a restricted space
* [NAMASTE](https://confluence.ucop.edu/download/attachments/14254149/NamasteSpec.pdf) redirects to a site where you can [search (Confluence?) spaces](https://ucopedu.atlassian.net/wiki/spaces)

**Comment by awoods** [comment]
Thanks for keeping an eye on the spec, @max-moser .
These two issues have been resolved in the `main` branch, but not yet released. See:
- https://github.com/OCFL/spec/issues/623
- https://github.com/OCFL/spec/issues/627
