### ISSUE TITLE
Skewed links in spec

### ISSUE THREAD

**Issue by ross-spencer** [OCFL/spec#653]
Looking at [the spec](https://ocfl.io/1.1/spec), it looks like there is skew on two links, they just resolve to the underlying CMS/publishing platform they started life on. The following links:

[PairTree] Pairtrees for Object Storage. J. Kunze; M. Haye; E. Hetzner; M. Reyes; C. Snavely. 12 August 2008. URL: https://confluence.ucop.edu/display/Curation/PairTree

[NAMASTE] Directory Description with Namaste Tags. J. Kunze.9 November 2009. URL: https://confluence.ucop.edu/download/attachments/14254149/NamasteSpec.pdf

(Both are available on the Internet Archive in some form so perhaps they can just link back to archive.org links to resolve this?)

**Comment by zimeon** [comment]
Dupe of https://github.com/OCFL/spec/issues/646 , both fixed in https://ocfl.io/draft/spec/ (although the wayback machine is down right now). Waiting on new version release, see #647

**Comment by ross-spencer** [comment]
Apologies for the noise @zimeon I didn't think to look in closed issues for dupes.
