### ISSUE TITLE
Add also to sentence in Section 3.4.2

### ISSUE THREAD

**Issue by rosy1280** [OCFL/spec#72]
Section 3.4.2 currently reads:

`Implementers may wish to store their file digests in a system external to their OCFL object stores at the point of ingest, to further safeguard against the possibility of malicious manipulation of file contents and digests.`

It should read:

`Implementers may also wish to store their file...`

**Comment by zimeon** [comment]
I suggest:
> Implementers MAY also store copies of their file digests...
just to make it really clear that this is an extra copy.
