### ISSUE TITLE
Is a `.keep` file required for an empty `logs` directory?

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#77]
The current https://ocfl.io/#basic-structure shows a `.keep` file in the `logs` directory. I don't think this should be necessary as we define the `logs` directory as the basic part of the OCFL Object structure

**Comment by ahankinson** [comment]
I think that was just to differentiate between a file and a folder in the structure. We could suffix directories with a '/', however, if we wanted to be clear about it.

Since `logs` is no longer strictly required, should we include it in a basic structure diagram anyway?

**Comment by zimeon** [comment]
As currently written, the `logs` directory is optional and this the minimal structure should not show it or the `.keep` file.
