### ISSUE TITLE
Use SHA512 as digest algorithm

### ISSUE THREAD

**Issue by zimeon** [OCFL/spec#8]
How do we decide what digest is best as the built-in one for deduping? I note an article https://medium.com/@davidtstrauss/stop-using-sha-256-6adbb55c608 that argues that sha512 is quicker to compute than sha256 and thus that, even if you want to avoid the full length of sha512, sha512/256 (a 256 bit truncation of sha512) is thus better than sha256.

**Comment by ahankinson** [comment]
512 sounds good to me. That's a great article.

**Comment by zimeon** [comment]
The speed comment above was news to me but is borne out from a few simple tests on my laptop:

```
simeon@RottenApple ~> gshred -s 1G - > a
simeon@RottenApple ~> { time sha256sum a; } 2>&1 | grep real; 
real	0m6.574s
simeon@RottenApple ~> { time sha256sum a; } 2>&1 | grep real; 
real	0m6.613s
simeon@RottenApple ~> { time shasum -a256 a; } 2>&1 | grep real; 
real	0m6.680s
simeon@RottenApple ~> { time shasum -a256 a; } 2>&1 | grep real; 
real	0m6.598s
simeon@RottenApple ~> { time shasum -a512 a; } 2>&1 | grep real; 
real	0m4.804s
simeon@RottenApple ~> { time shasum -a512 a; } 2>&1 | grep real; 
real	0m4.780s
```

**Comment by jamesmooneybodleian** [comment]
That's very interesting and was news to me. Cheers Zimeon.

**Comment by ahankinson** [comment]
Sounds good to me. Shall we change the title of this and make it into an actionable item for the spec?

**Comment by jamesmooneybodleian** [comment]
I think so. Just one open question, use the full 512bit hash? or truncate to 256bit? 

Personally I would just go with the full 512bit hash.

**Comment by ahankinson** [comment]
The full 512 sounds good to me too.

**Comment by awoods** [comment]
Agreed: sha-512

**Comment by neilsjefferies** [comment]
Agreed: sha-512

**Comment by rosy1280** [comment]
+1

**Comment by julianmorley** [comment]
+1

**Comment by zimeon** [comment]
Implemented in current spec draft. DONE
